### ISSUE TITLE
I  generate opencl.bin files failed when  I use MTK socs (6757,6771) ,but it passed on msm8953 

### ISSUE THREAD

**Issue by sunzhe09** [XiaoMi/mace#100]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution ( Linux Ubuntu 16.04)**:
- **NDK version( 16b)**:
- **GCC version(4.9.3)**:
- **MACE version (master)**:
- **Python version(2.7)**: 
- **Bazel version (0.13.0)**:

### Model deploy file (*.yml)
```yaml
library_name: deeplab-v3-plus-mobilenet-v2

target_abis: [armeabi-v7a, arm64-v8a]

#target_socs: [msm8953]
target_socs: [mt6771]
#target_socs: [mt6757]

model_graph_format: code

model_data_format: code

models:

  deeplab_v3_plus_mobilenet_v2:

    platform: tensorflow

    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/deeplab-v3-plus/deeplab-v3-plus-mobilenet-v2.pb

    model_sha256_checksum: 0299ad261a2455e687b9c80acb815db1e62ccc38ec1ba5166783271bd150f316

    subgraphs:

      - input_tensors: sub_7

        output_tensors: ResizeBilinear_2

        input_shapes: 1,513,513,3

        output_shapes: 1,65,65,21

    runtime: cpu+gpu

    limit_opencl_kernel_time: 0

    nnlib_graph_mode: 0

    obfuscate: 0

    winograd: 0


```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. 
 python tools/converter.py convert  --config='/home/sunzhe/mace/mace-models/deeplab-v3-plus/deeplab-v3-plus-mobilenet-v2.yml' 
python tools/converter.py run  --config='/home/sunzhe/mace/mace-models/deeplab-v3-plus/deeplab-v3-plus-mobilenet-v2.yml'  --validate 

```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
python tools/converter.py run  --config='/home/sunzhe/mace/mace-models/deeplab-v3-plus/deeplab-v3-plus-mobilenet-v2.yml'  --validate 
* Build //mace/tools/validation:mace_run_static with ABI armeabi-v7a
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //mace/tools/validation:mace_run_static (2 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 381.163s, Critical Path: 10.90s
INFO: 131 processes: 131 linux-sandbox.
INFO: Build completed successfully, 132 total actions
Build done!

********************************************************************
          Run model deeplab_v3_plus_mobilenet_v2 on PACM00          
********************************************************************

* Tuning, it may take some time...
Generate input file:  builds/deeplab-v3-plus-mobilenet-v2/_tmp/deeplab_v3_plus_mobilenet_v2/8a42938bed17baba5886a3c971c15c68/PACM00_mt6771/armeabi-v7a/model_input_sub_7
Generate input file done.
* Run 'deeplab_v3_plus_mobilenet_v2' with round=0, restart_round=1, tuning=True, out_of_range_check=False, omp_num_threads=-1, cpu_affinity_policy=1, gpu_perf_hint=3, gpu_priority_hint=3
Push builds/deeplab-v3-plus-mobilenet-v2/_tmp/deeplab_v3_plus_mobilenet_v2/8a42938bed17baba5886a3c971c15c68/PACM00_mt6771/armeabi-v7a/model_input_sub_7 to /data/local/tmp/mace_run
Push builds/deeplab-v3-plus-mobilenet-v2/model/deeplab_v3_plus_mobilenet_v2.data to /data/local/tmp/mace_run
Push third_party/nnlib/libhexagon_controller.so to /data/local/tmp/mace_run
Push builds/deeplab-v3-plus-mobilenet-v2/model/deeplab_v3_plus_mobilenet_v2.pb to /data/local/tmp/mace_run/deeplab_v3_plus_mobilenet_v2.pb
Push builds/deeplab-v3-plus-mobilenet-v2/_tmp/armeabi-v7a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-deeplab_v3_plus_mobilenet_v2-1531982644.45 to /data/local/tmp/mace_run/cmd_file-deeplab_v3_plus_mobilenet_v2-1531982644.45
WARNING: linker: Warning: unable to normalize "external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/lib/linux/arm"
I mace_run.cc:428 model name: deeplab_v3_plus_mobilenet_v2
I mace_run.cc:429 mace version: v0.8.1-148-g15a34cc-20180718
I mace_run.cc:430 input node: sub_7
I mace_run.cc:431 input shape: 1,513,513,3
I mace_run.cc:432 output node: ResizeBilinear_2
I mace_run.cc:433 output shape: 1,65,65,21
I mace_run.cc:434 input_file: /data/local/tmp/mace_run/model_input
I mace_run.cc:435 output_file: /data/local/tmp/mace_run/model_out
I mace_run.cc:436 model_data_file: /data/local/tmp/mace_run/deeplab_v3_plus_mobilenet_v2.data
I mace_run.cc:437 model_file: /data/local/tmp/mace_run/deeplab_v3_plus_mobilenet_v2.pb
I mace_run.cc:438 device: GPU
I mace_run.cc:439 round: 0
I mace_run.cc:440 restart_round: 1
I mace_run.cc:441 gpu_perf_hint: 3
I mace_run.cc:442 gpu_priority_hint: 3
I mace_run.cc:443 omp_num_threads: -1
I mace_run.cc:444 cpu_affinity_policy: 1
I mace_run.cc:467 restart round 0
W opencl_runtime.cc:302 There is no precompiled OpenCL binary file in [/data/local/tmp/mace_run/]
I mace.cc:382 Create MaceEngine from model pb
I mace.cc:165 Creating MaceEngine, MACE version: v0.8.1-148-g15a34cc-20180718
I mace.cc:236 Loading Model Data
I mace.cc:173 Initializing MaceEngine
F opencl_wrapper.cc:727 'func' Must be non NULL
Aborted
ERROR: [Mace Run] Mace run failed.

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
