### ISSUE TITLE
Something went wrong when I optimized my model of tensorflow with Graph Transform Tool

### ISSUE THREAD

**Issue by wuyajun19900627** [XiaoMi/mace#104]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:r15c
- **GCC version(if compiling for host, e.g., 5.4.0)**:not known yet
- **MACE version (Use the command: git describe --long --tags)**:v0.8.1-143-gfc1c855
- **Python version(2.7)**: Python 2.7.12
- **Bazel version (e.g., 0.13.0)**:not known

### Model deploy file (*.yml)
```yaml

library_name: test
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: /home/user/wuyajun/model/output_graph.pb
    model_sha256_checksum: a123ab19fc3048ac7a4fd5e37d819cc369cff8a80f55b5fdac25144ca0c5625c
    subgraphs:
      - input_tensors:
          - Placeholder
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - final_result
        output_shapes:
          - 1,6
    runtime: cpu+gpu
    winograd: 0

......
```

### Describe the problem
Something went wrong when I optimized my model of tensorflow with Graph Transform Tool

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd tensorflow/
2. bazel build tensorflow/tools/graph_transforms:transform_graph
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash

[bazel INFO src/main/cpp/option_processor.cc:235] Looking for master bazelrcs in the following three paths: /home/user/wuyajun/tensorflow/tools/bazel.rc, , 
[bazel INFO src/main/cpp/rc_file.cc:53] Parsing the RcFile /home/user/wuyajun/tensorflow/tools/bazel.rc
[bazel INFO src/main/cpp/rc_file.cc:53] Parsing the RcFile /home/user/wuyajun/tensorflow/.bazelrc
[bazel INFO src/main/cpp/rc_file.cc:53] Parsing the RcFile /Users/rgbitx/tensorflow/.tf_configure.bazelrc
[bazel FATAL src/main/cpp/blaze.cc:1263] Unexpected error reading .blazerc file '/Users/rgbitx/tensorflow/.tf_configure.bazelrc'


```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
