### ISSUE TITLE
为什么用python运行mobilenet-v1-1.0.pb模型的识别结果与mace识别结果不一样呢？

### ISSUE THREAD

**Issue by TinyLina** [XiaoMi/mace#120]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yml
library_name: mobilenet-v1
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```
### Describe the problem
我用python在linux下运行mobilenet-v1-1.0.pb进行物体识别，对同一张图像它的识别结果与同一个模型在mace下的结果相差很大（测试了多张图像）。mace下的识别结果较为准确，是鼠标就识别为鼠标，键盘就识别为键盘。但python运行该模型时识别结果就相差很多。我是通过得到运行模型时的返回值，与cacheLabel.txt文件比较得到的结果。（mobilenet_v1_1.0_224_frozen.pb，mobilenet-v1-1.0.pb两个模型文件都测试了，结果相同）

我又测试mobilenet-v2-1.0.pb与mobilenet_v2_1.0_224_frozen.pb这两个模型，在tensorflow下得到的结果也不对。而且我识别了三张图像，识别结果置信度最高的居然在同一个索引（三张图像相差很大，分别是鼠标，键盘，手机），求解是怎么回事？

.pb模型文件我是从mace-models中.yml文件中的链接下载的

### python code
```py
def test_with_frozen_pb(imglist, input_w_h, frozen_graph, output_node_names, use_gpu, output_dir):
    import tensorflow as tf
    import numpy as np
    import cv2
    import os   

    os.environ['CUDA_VISIBLE_DEVICES'] = ''
    if use_gpu == 1:
        os.environ['CUDA_VISIBLE_DEVICES'] = '0'

    with tf.gfile.GFile(frozen_graph, "rb") as f:
        restored_graph_def = tf.GraphDef()
        restored_graph_def.ParseFromString(f.read())

    tf.import_graph_def(
        restored_graph_def,
        input_map=None,
        return_elements=None,
        name=""
    )

    graph = tf.get_default_graph()
    image = graph.get_tensor_by_name("input:0")
    output = graph.get_tensor_by_name("%s:0" % output_node_names)

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    file = open(imglist, "r")
    alllines=file.readlines();
    file.close();

    nCount = 0;
    time_all = 0;
    for line in alllines:
        print '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
        #print 'line:{}'.format(line)
        im_name = line[(line.rfind('/')+1):];
        im_name = im_name[:im_name.rfind('.')];
	out_name = '{:s}.txt'.format(im_name)
        im_name = '{:s}.jpg'.format(im_name)
        input_path = line[:line.rfind('/')];
        im_file = '{:s}/{:s}'.format(input_path,im_name)
        print 'input_file:{}'.format(im_file)

        nCount = nCount+1;    
        if nCount%50 == 0:
            print 'load img:{}...'.format(nCount)

        image_0 = cv2.imread(im_file)
        w, h, _ = image_0.shape
        image_ = cv2.resize(image_0, (input_w_h, input_w_h), interpolation=cv2.INTER_AREA)

        with tf.Session() as sess:
            heatmaps = sess.run(output, feed_dict={image: [image_]})
	    print 'heatmaps is :', heatmaps
	    np.savetxt(out_name, heatmaps, fmt="%.5f", delimiter=",")

if __name__ == '__main__':
    use_gpu = 0;
    model = "./mobilenet_v1_1.0_224_frozen.pb"
    model_outlayer = "MobilenetV1/Predictions/Reshape_1"
    imglist = "img.txt"
    output_dir = "./test/"

    test_with_frozen_pb( imglist, 224, model, model_outlayer, use_gpu, output_dir )
```
