### ISSUE TITLE
TypeError: object of type 'NoneType' has no len() occurs When convert tensorflow model.

### ISSUE THREAD

**Issue by wuyajun19900627** [XiaoMi/mace#125]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
library_name: mobilenet
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
mobilenet_v2:
    platform: tensorflow
    model_file_path: /home/user/wuyajun/model_tensorflow/output_model.pb
    model_sha256_checksum: 3b531013fa8d74b7da48b8d612bef3c3c4d63129c6be4108f4203c482aa0e0e9
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,5
    runtime: cpu+gpu
    winograd: 0
```

### Describe the problem
TypeError: object of type 'NoneType' has no len() occurs When convert tensorflow model.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Traceback (most recent call last):
  File "tools/converter.py", line 1580, in <module>
    flags.func(flags)
  File "tools/converter.py", line 781, in convert_func
    configs = format_model_config(flags)
  File "tools/converter.py", line 351, in format_model_config
    mace_check(len(model_names) > 0, ModuleName.YAML_CONFIG,
TypeError: object of type 'NoneType' has no len()

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by nolanliou** [comment]
```
models:
  mobilenet_v2:
    platform: tensorflow
    model_file_path: /home/user/wuyajun/model_tensorflow/output_model.pb
    model_sha256_checksum: 3b531013fa8d74b7da48b8d612bef3c3c4d63129c6be4108f4203c482aa0e0e9
```
注意yaml文件的格式
