### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rogerou** [XiaoMi/mace#130]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:MacOS
- **NDK version(e.g., 15c)**:r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:0.81
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.15

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: 180723_alpha_landmark
target_abis: [armeabi-v7a]
model_graph_format: code
model_data_format: code
models:
  mobilenet_v1: # model tag, which will be used in model loading and must be specific.
    platform: tensorflow
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /Users/ouzhijie/Downloads/180726_alpha_landmark.pb
    # sha256_checksum of your model's pb file.
    # use this command to get the sha256_checksum: sha256sum path/to/your/pb/file
    model_sha256_checksum: 602d722603c869777536b8dcfe1dacf85d2d1a1a967f1212fad3d4721b7ac62f 
    # define your model's interface
    # if there multiple inputs or outputs, write like blow:
    # subgraphs:
    # - input_tensors:
    #     - input0
    #     - input1
    #   input_shapes:
    #     - 1,224,224,3
    #     - 1,224,224,3
    #    output_tensors:
    #      - output0
    #      - output1
    #    output_shapes:
    #      - 1,1001
    #      - 1,1001
    subgraphs:
      - input_tensors:
          - tower_0/MobilenetV2/input
        input_shapes:
          - 1,128,128,3
        output_tensors:
          - tower_0/kpts/out/BatchNorm/FusedBatchNorm
          - tower_0/pose/fc2/BiasAdd
          - tower_0/face/fc2/BiasAdd
        output_shapes:
          - 1,64,64,106
          - 1,3
          - 1,2
    # cpu, gpu or cpu+gpu
    runtime: cpu+gpu
    winograd: 4
......
```

### Describe the problem
convert success and run (Segmentation fault)
### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py run --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Generate input file:  builds/180723_alpha_landmark/_tmp/mobilenet_v1/a2b844c7145032ec0f23b7f5c4a163da/general/armeabi-v7a/model_input_tower_0_MobilenetV2_input
Generate input file done.
* Run 'mobilenet_v1' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/180723_alpha_landmark/_tmp/mobilenet_v1/a2b844c7145032ec0f23b7f5c4a163da/general/armeabi-v7a/model_input_tower_0_MobilenetV2_input to /data/local/tmp/mace_run
Push third_party/nnlib/libhexagon_controller.so to /data/local/tmp/mace_run
Push builds/180723_alpha_landmark/_tmp/armeabi-v7a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-mobilenet_v1-1532611862.8 to /data/local/tmp/mace_run/cmd_file-mobilenet_v1-1532611862.8
WARNING: linker: Warning: unable to normalize "external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/5.0.300080/lib/linux/arm"
I mace_run.cc:428 model name: mobilenet_v1
I mace_run.cc:429 mace version: v0.8.1-183-g7a9ee4c-20180726
I mace_run.cc:430 input node: tower_0/MobilenetV2/input
I mace_run.cc:431 input shape: 1,128,128,3
I mace_run.cc:432 output node: tower_0/kpts/out/BatchNorm/FusedBatchNorm,tower_0/pose/fc2/BiasAdd,tower_0/face/fc2/BiasAdd
I mace_run.cc:433 output shape: 1,64,64,106:1,3:1,2
I mace_run.cc:434 input_file: /data/local/tmp/mace_run/model_input
I mace_run.cc:435 output_file: /data/local/tmp/mace_run/model_out
I mace_run.cc:436 model_data_file: /data/local/tmp/mace_run/mobilenet_v1.data
I mace_run.cc:437 model_file:
I mace_run.cc:438 device: CPU
I mace_run.cc:439 round: 1
I mace_run.cc:440 restart_round: 1
I mace_run.cc:441 gpu_perf_hint: 3
I mace_run.cc:442 gpu_priority_hint: 3
I mace_run.cc:443 omp_num_threads: -1
I mace_run.cc:444 cpu_affinity_policy: 1
I mace_run.cc:467 restart round 0
I mace.cc:165 Creating MaceEngine, MACE version: v0.8.1-183-g7a9ee4c-20180726
I mace.cc:173 Initializing MaceEngine
I mace_run.cc:273 Total init latency: 32.571 ms
I mace_run.cc:313 Warm up run
Segmentation fault
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1248, in run_mace
    target_soc, serial_num)
  File "tools/converter.py", line 1145, in run_specific_target
    link_dynamic=link_dynamic,
  File "/Users/ouzhijie/Documents/WorkSpace/mace/tools/sh_commands.py", line 766, in tuning_run
    _err_to_out=True)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_139:

  RAN: /Users/ouzhijie/Library/Android/sdk/platform-tools/adb -s 479b7c31 shell sh /data/local/tmp/mace_run/cmd_file-mobilenet_v1-1532611862.8

  STDOUT:


  STDERR:
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
