### ISSUE TITLE
在运行Android的Demo的时候报错

### ISSUE THREAD

**Issue by yeyupiaoling** [XiaoMi/mace#159]
## 系统环境
 - Windows 10
 - 运行NDK版本：17b
 - 编译的NDK版本：15c
 - MACE版本：v0.9.0-12-gba4157f7
 - Python版本：2.7
 - Bazel版本：0.13.0

## 模型部署文件
```
library_name: mobilenet-v2
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  mobilenet_v2:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet-v2-1.0.pb
    model_sha256_checksum: 369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

## 描述问题
在Android Studio运行的时候报错

## 问题复现
执行build.sh，然后在Android Studio运行

## 主要报错信息如下：
```
classify.cc:106: error: undefined reference to 'mace::FileStorageFactory::FileStorageFactory(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
image_classify.cc:107: error: undefined reference to 'mace::SetKVStorageFactory(std::__ndk1::shared_ptr<mace::KVStorageFactory>)'
image_classify.cc:203: error: undefined reference to 'mace::MaceTensor::MaceTensor(std::__ndk1::vector<long long, std::__ndk1::allocator<long long> > const&, std::__ndk1::shared_ptr<float>)'
image_classify.cc:208: error: undefined reference to 'mace::MaceTensor::MaceTensor(std::__ndk1::vector<long long, std::__ndk1::allocator<long long> > const&, std::__ndk1::shared_ptr<float>)'
image_classify.cc:211: error: undefined reference to 'mace::MaceEngine::Run(std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, ......
```

我看了这些类和函数都是有的，这是为什么呢？
