### ISSUE TITLE
自己的模型在GPU上会crash，CPU上则正常运行

### ISSUE THREAD

**Issue by qiaowei1214** [XiaoMi/mace#183]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Mac10.12.6
- **NDK version(e.g., 15c)**:r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:v0.9.0-111-g60e4f28
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.13.0

### Model deploy file (*.yml)
```yaml
library_name: openPose
target_abis: [armeabi-v7a]
model_graph_format: code
model_data_format: code
models:
  Openpose:
    platform: tensorflow
    model_file_path: /mace/mace-models/openPose/graph_opt.pb
    model_sha256_checksum: 51f84ea82b3d0143dd4cf362e018c125e832c64771908ee8766fbd8b0328008d
    subgraphs:
      - input_tensors:
          - image
        input_shapes:
          - 1,368,368,3
        output_tensors:
          - Openpose/concat_stage7
        output_shapes:
          - 1,46,46,57
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
