### ISSUE TITLE
Tensorflow 1.10

### ISSUE THREAD

**Issue by tpr11** [XiaoMi/mace#213]
Are there any future plans to include support for tensorflow 1.10 models?

**Comment by tataganesh95** [comment]
@tpr11  Which models are you talking about?

**Comment by tpr11** [comment]
@tataganesh95 Sorry for the ambiguity. The python conversion script for tensorflow model does not work if the local tensorflow version is 1.10, while it works fine with tensorflow==1.6 (as specified in the environment requirements, using the specified version for all other requirements).
  
For example, using this config file:
```
library_name: mobilenet-v2
target_abis: [host]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v2:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet-v2-1.0.pb
    model_sha256_checksum: 369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,1001
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
    runtime: cpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```
, and issuing the command `python2 tools/converter.py convert --config=<config file>` from within the correct MACE directory produces the error found in this log file: [log.txt](https://github.com/XiaoMi/mace/files/2450009/log.txt) 
, if the tensorflow version is 1.10, but converts it successfully if the 1.6 version is installed.

I was wondering if there are any plans to update this particular requirement.
