### ISSUE TITLE
A/MACE: eltwise.h:815 Check failed

### ISSUE THREAD

**Issue by imu-hupeng** [XiaoMi/mace#22]
安卓调用的时候库的时候出现如下错误：
```
I/MACE: mace.cc:127 Creating MaceEngine, MACE version: unknown-20180630
I/MACE: mace.cc:135 Initializing MaceEngine
A/MACE: eltwise.h:815 Check failed: (input0->dim_size() == 4) && ((input1->dim_size() == 0) || (input1->dim_size() == 4 && input1->dim(1) == input0->dim(1) && (input1->dim(0) == input0->dim(0) || input1->dim(0) == 1)) || (input1->dim_size() == 1 && input1->dim(0) == input0->dim(1))) only support broadcast channel dimension
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 15844 (ang.imuqueryapp)

        [ 06-30 17:31:34.473   439:  439 W/         ]
        debuggerd: handling request: pid=15844 uid=10143 gid=10143 tid=15844
Application terminated.
```
android C++ jni部分代码如下：
```c++
namespace {
    struct ModelInfo {
        std::string input_name;
        std::string output_name;
        std::vector<int64_t> input_shape;
        std::vector<int64_t> output_shape;
    };


    struct MaceContext {
        std::shared_ptr<mace::MaceEngine> engine;
        std::shared_ptr<mace::KVStorageFactory> storage_factory;
        std::string model_name="ecard_captcha_crack";
        mace::DeviceType device_type = mace::DeviceType::CPU;
        std::map<std::string, ModelInfo> model_infos = {
                {"ecard_captcha_crack", {"input", "output", {1, 218, 82, 3}, {5, 10}}},
        };
    };

    mace::DeviceType ParseDeviceType(const std::string &device) {
        if (device.compare("CPU") == 0) {
            return mace::DeviceType::CPU;
        } else if (device.compare("GPU") == 0) {
            return mace::DeviceType::GPU;
        } else if (device.compare("HEXAGON") == 0) {
            return mace::DeviceType::HEXAGON;
        } else {
            return mace::DeviceType::CPU;
        }
    }

    MaceContext& GetMaceContext() {
        // stay for the app's life time, only initialize once
        static auto *mace_context = new MaceContext;

        return *mace_context;
    }

}  // namespace

JNIEXPORT jint JNICALL
Java_me_hupeng_sdk_ecardcaptchacrack_ECardCaptchaCrack2_createEngine(JNIEnv *env, jobject instance) {

    MaceContext &mace_context = GetMaceContext();

    auto model_info_iter =
            mace_context.model_infos.find(mace_context.model_name);


    const ModelInfo &model_info = model_info_iter->second;
    const std::string &input_name = model_info.input_name;
    const std::string &output_name = model_info.output_name;
    const std::vector<int64_t> &input_shape = model_info.input_shape;
    const std::vector<int64_t> &output_shape = model_info.output_shape;

    mace::MaceStatus create_engine_status =
            CreateMaceEngineFromCode(mace_context.model_name,
                                     std::string(),
                                     input_name,
                                     output_name,
                                     mace_context.device_type,
                                     &mace_context.engine);
    return create_engine_status == mace::MaceStatus::MACE_SUCCESS ?
           JNI_OK : JNI_ERR;
}


JNIEXPORT jstring JNICALL
Java_me_hupeng_sdk_ecardcaptchacrack_ECardCaptchaCrack2_crack(JNIEnv *env, jobject instance,
                                                              jfloatArray input_data) {
    MaceContext &mace_context = GetMaceContext();
    //  prepare input and output
    auto model_info_iter =
            mace_context.model_infos.find(mace_context.model_name);


    const ModelInfo &model_info = model_info_iter->second;
    const std::string &input_name = model_info.input_name;
    const std::string &output_name = model_info.output_name;
    const std::vector<int64_t> &input_shape = model_info.input_shape;
    const std::vector<int64_t> &output_shape = model_info.output_shape;
    const int64_t input_size =
            std::accumulate(input_shape.begin(), input_shape.end(), 1,
                            std::multiplies<int64_t>());
    const int64_t output_size =
            std::accumulate(output_shape.begin(), output_shape.end(), 1,
                            std::multiplies<int64_t>());

    std::map<std::string, mace::MaceTensor> inputs;
    std::map<std::string, mace::MaceTensor> outputs;

    jfloat *input_data_ptr  = env->GetFloatArrayElements(input_data, NULL);
    jsize length = env->GetArrayLength(input_data);

    auto buffer_in = std::shared_ptr<float>(new float[input_size],
                                            std::default_delete<float[]>());
    std::copy_n(input_data_ptr, input_size, buffer_in.get());
    env->ReleaseFloatArrayElements(input_data, input_data_ptr, 0);
    inputs[input_name] = mace::MaceTensor(input_shape, buffer_in);

    // construct output
    auto buffer_out = std::shared_ptr<float>(new float[output_size],
                                             std::default_delete<float[]>());
    outputs[output_name] = mace::MaceTensor(output_shape, buffer_out);

    // run model
    mace_context.engine->Run(inputs, &outputs);

    // transform output
//    jfloatArray jOutputData = env->NewFloatArray(output_size);  // allocate
//    if (jOutputData == nullptr) return nullptr;
//    env->SetFloatArrayRegion(jOutputData, 0, output_size,
//                             outputs[output_name].data().get());  // copy
//

    return env->NewStringUTF("hello world");
}
```
运行到下面一行的时候crash
```
 mace_context.engine->Run(inputs, &outputs);
```
yaml文件如下：
```
# The name of library
library_name: ppnet
target_abis: [arm64-v8a,armeabi-v7a]
embed_model_data: 1
# The build mode for model(s).
# 'code' stand for transfer model(s) into cpp code, 'proto' for model(s) in protobuf file(s).
build_type: code
linkshared: 0
# One yaml config file can contain multi models' config message.
models:
  ecard_captcha_crack: # model tag, which will be used in model loading and must be specific.
    platform: tensorflow
    # support local path, http:// and https://
    model_file_path: /home/hupeng/tf_model_opt.pb 
    model_sha256_checksum: 05b347ab8ff512ebd5ca467e64c33809b2a6b259be15b29eec07591d3c6ddda9
    subgraphs:
      - input_tensors: input
        input_shapes: 1,218,82,3
        output_tensors: output
        output_shapes: 5,10
    runtime: cpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

```
