### ISSUE TITLE
runtime error while running mace with opencl

### ISSUE THREAD

**Issue by reasonsolo** [XiaoMi/mace#232]
I'm trying to run mace on my device(mali GPU).

### System information
-  android 7.12 on RK3399
-  ndk-17c with clang toolset
-  MACE version: v0.9.0-282-g9b78e12-20181029

By ` python tools/converter.py run --config=mace-models/mobilenet-v2/profile.yaml   --validate
`, I got following output.

```
WARNING: linker: /system/lib64/libmace.so: unused DT entry: type 0xf arg 0x13489f
I mace.cc:629 Create MaceEngine from model pb
I mace.cc:387 Creating MaceEngine, MACE version: v0.9.0-282-g9b78e12-20181029
I mace.cc:483 Loading Model Data
I mace.cc:413 Initializing MaceEngine
W tensor.h:286 mobilenet_v2/Flatten/flatten/strided_slice:0: Resize buffer from size 65 to 66
W tensor.h:286 mobilenet_v2/Flatten/flatten/Reshape/shape:0: Resize buffer from size 66 to 68
F tensor.h:226 Check failed: has_opencl_image()  do not have image
Aborted 
```

Appraciate it if any one could give me a opencl enabled mace tutorial.

my model yaml
```
library_name: profile-v1031
target_abis: [arm64-v8a]
target_socs: [rk3399]
model_graph_format: file
model_data_format: file
models:
  profile_v1031:
    platform: tensorflow
    model_file_path: /tmp/profile_v1031.pb
    model_sha256_checksum: f63570f2d76fbbb99621fd24413451313b62874d9053b72583962c7d7a4be71e
    subgraphs:
      - input_tensors:
          - input_image
        input_shapes:
          - 1,96,96,3
        output_tensors:
          - gender
          - age
        output_shapes:
          - 1,2
          - 1,101
    runtime: gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 1
    winograd: 0
    cl_mem_type: image
```

**Comment by reasonsolo** [comment]
my model yaml

```
library_name: profile-v1031
target_abis: [arm64-v8a]
target_socs: [rk3399]
model_graph_format: file
model_data_format: file
models:
  profile_v1031:
    platform: tensorflow
    model_file_path: /tmp/profile_v1031.pb
    model_sha256_checksum: f63570f2d76fbbb99621fd24413451313b62874d9053b72583962c7d7a4be71e
    subgraphs:
      - input_tensors:
          - input_image
        input_shapes:
          - 1,96,96,3
        output_tensors:
          - gender
          - age
        output_shapes:
          - 1,2
          - 1,101
    runtime: gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 1
    winograd: 0
    cl_mem_type: image

```
