### ISSUE TITLE
使用不同的输入数据运行模型,后续的结果会受第一次运行的影响

### ISSUE THREAD

**Issue by hmztl976** [XiaoMi/mace#253]
### System information
- **Linux Ubuntu 16.04 x64
- **NDK version 15c
- **gcc version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~16.04)
- **MACE version 0.9.0
- **Python version 2.7.12
- **Bazel version (0.13.0)

### Model deploy file (*.yml)
```yaml
library_name: face-detection
model_data_format: file
model_graph_format: file
models:
  face_detection_pnet:
    dsp_mode: 0
    limit_opencl_kernel_time: 0
    model_file_path: MTCNN_1.pb
    model_sha256_checksum: feffc1b4a125aa7ec968df9adb9e0e3131fdd1c24ca6fd54e3280cd41923e6eb
    obfuscate: 0
    platform: tensorflow
    runtime: cpu
    subgraphs:
    - input_shapes: ['1,640,480,3']
      input_tensors: ['pnet/input:0']
      output_shapes: ['1,640,480,4', '1,640,480,2']
      output_tensors: ['pnet/conv4-2/BiasAdd:0', 'pnet/prob1:0']
    winograd: 0
```

### Describe the problem
附件里包含test.cpp, test.py, mat.dat, model_1.pb.
mat.dat存储了2个数据:mat0,mat1.
初始化模型后先输入mat0运行再输入mat1运行和初始化模型后直接输入mat1运行的结果不一致. 

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
3. 修改test.cpp和test.py中模型的路径.
4. 编译test.cpp并运行可以看到两个test函数运行结果不一致.
5. 运行test.py的结果 和test.cpp中test2函数结果作为比对.
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
I mace/libmace/mace.cc:426] Create MaceEngine from model pb
I mace/libmace/mace.cc:203] Creating MaceEngine, MACE version: v0.9.0-0-gb23889d-20181016
I mace/libmace/mace.cc:280] Loading Model Data
I mace/libmace/mace.cc:211] Initializing MaceEngine
out1[0.99912816, 0.00087186234, 0.99937159, 0.00062844495, 0.9973374, 0.0026625721, 0.99970007, 0.0002999393, 0.99980611, 0.00019391265, 0.99722064, 0.0027793942, 0.9986558, 0.001344224, 0.99961179, 0.00038826614, 0.99354374, 0.0064563132, 0.99963737, 0.00036262983, 0.99731404, 0.0026859767, 0.99664742, 0.003352612, 0.98029321, 0.01970678, 0.98629606, 0.013703953, 0.96460766, 0.035392415;
...]
---------------------------------------
I mace/libmace/mace.cc:426] Create MaceEngine from model pb
I mace/libmace/mace.cc:203] Creating MaceEngine, MACE version: v0.9.0-0-gb23889d-20181016
I mace/libmace/mace.cc:299] Destroying MaceEngine
I mace/libmace/mace.cc:280] Loading Model Data
I mace/libmace/mace.cc:211] Initializing MaceEngine
out1[0.99999976, 2.1742147e-07, 0.9999702, 2.9854345e-05, 0.99990475, 9.5206509e-05, 0.99999976, 1.8975182e-07, 0.99995935, 4.0687748e-05, 0.99998009, 1.9865358e-05, 0.92718399, 0.072815977, 0.99955648, 0.00044347602, 0.99765837, 0.0023416081, 0.99928051, 0.00071946438, 0.99997342, 2.6556812e-05, 0.99999905, 9.9990643e-07, 1, 5.1037038e-08, 0.99999225, 7.6891756e-06, 0.99940693, 0.00059308269;
...]
```

### Additional context
[test.zip](https://github.com/XiaoMi/mace/files/2564328/test.zip)
