### ISSUE TITLE
Failure on DSP

### ISSUE THREAD

**Issue by w-adamski** [XiaoMi/mace#274]
### System information
- **OS Platform and Distribution**: Open-Q 660 HDK Hardware Development Kit (Android 7.1.1)
- **MACE version**: commit a46158c86aeb3b9dc0bbca8a44d272f258f5b538
- **NDK version, GCC version, Python version, Bazel version**: from mace-dev docker image. ID: 3e13cb346e2e

### Model deploy file (*.yml)
https://github.com/XiaoMi/mace-models/blob/master/inception-v3/inception-v3-dsp.yml with changed target_abis and target_socs:
```yaml
library_name: inception-v3-dsp
target_abis: [arm64-v8a]
target_socs: [sdm660]
model_graph_format: file
model_data_format: file
models:
  inception_v3_dsp:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/inception-v3/inception-v3-q-2016.pb
    model_sha256_checksum: 185ff8738d3ebe2519fe15f066162004bb98ccd92e7cd7a7152b4c82f9451bdf
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,299,299,3
        output_tensors:
          - InceptionV3/Predictions/Reshape_1
        output_shapes:
          - 1,1,1,1001
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/keyboard_299x299.bin
    runtime: dsp
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 4
    obfuscate: 1
winograd: 0
```

### Describe the problem
Inference doesn't work on DSP. If fails on assert:
```
tensor.h:294 Check failed: raw_size() <= buffer_->size()
```
Debugging shows that buffer_->size() is 0. The same problem exists on other tried models (buffer_->size() is also 0).
The device is signed and in general other code on DSP works correctly.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config=inception-v3-dsp.yml
3. python tools/converter.py benchmark --config=inception-v3-dsp.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
root@f024c1be312c:/mace# python tools/converter.py benchmark --config=inception-v3-dsp.yml
* Build //mace/benchmark:benchmark_model_static with ABI arm64-v8a
v0.9.0-389-ga46158c-20181213
INFO: Analysed target //mace/benchmark:benchmark_model_static (22 packages loaded).
INFO: Found 1 target...
Target //mace/benchmark:benchmark_model_static up-to-date:
  bazel-bin/mace/benchmark/benchmark_model_static
INFO: Elapsed time: 94.800s, Critical Path: 22.87s
INFO: 293 processes, local.
INFO: Build completed successfully, 297 total actions
Build done!

**********************************************************************
          Benchmark model inception_v3_dsp on sdm660forarm64          
**********************************************************************

Generate input file:  builds/inception-v3-dsp/_tmp/inception_v3_dsp/9e96aeebd42480e7d6cf18ec9e991410/sdm660forarm64_sdm660/arm64-v8a/model_input_input
Generate input file done.
* Benchmark for inception_v3_dsp
Push builds/inception-v3-dsp/_tmp/inception_v3_dsp/9e96aeebd42480e7d6cf18ec9e991410/sdm660forarm64_sdm660/arm64-v8a/model_input_input to /data/local/tmp/mace_run
Push builds/inception-v3-dsp/model/inception_v3_dsp.data to /data/local/tmp/mace_run
Push builds/inception-v3-dsp/model/inception_v3_dsp.pb to /data/local/tmp/mace_run/inception_v3_dsp.pb
Push builds/inception-v3-dsp/_tmp/arm64-v8a/benchmark_model_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-inception_v3_dsp-1544692586.43 to /data/local/tmp/mace_run/cmd_file-inception_v3_dsp-1544692586.43
WARNING: linker: /data/local/tmp/mace_run/benchmark_model_static: unused DT entry: type 0xf arg 0x6a6
I benchmark_model.cc:216 Model name: [inception_v3_dsp]
I benchmark_model.cc:217 Model_file: /data/local/tmp/mace_run/inception_v3_dsp.pb
I benchmark_model.cc:218 Device: [HEXAGON]
I benchmark_model.cc:219 gpu_perf_hint: [3]
I benchmark_model.cc:220 gpu_priority_hint: [3]
I benchmark_model.cc:221 omp_num_threads: [-1]
I benchmark_model.cc:222 cpu_affinity_policy: [1]
I benchmark_model.cc:223 Input node: [input]
I benchmark_model.cc:224 Input shapes: [1,299,299,3]
I benchmark_model.cc:225 Output node: [InceptionV3/Predictions/Reshape_1]
I benchmark_model.cc:226 output shapes: [1,1,1,1001]
I benchmark_model.cc:227 Warmup runs: [1]
I benchmark_model.cc:228 Num runs: [100]
I benchmark_model.cc:229 Max run time: [10.0]
I mace.cc:731 Create MaceEngine from model pb
I mace.cc:389 Creating MaceEngine, MACE version: v0.9.0-389-ga46158c-20181213
I mace.cc:493 Loading Model Data
I mace.cc:415 Initializing MaceEngine
F tensor.h:294 Check failed: raw_size() <= buffer_->size() 
Aborted 
Benchmark done!
