### ISSUE TITLE
Try to build the caffemodel,but the script needed tensorflow

### ISSUE THREAD

**Issue by BUG1989** [XiaoMi/mace#29]
My deepLearning development framework is Caffe,When I use the tools/converter.py to build the squeezenet-v11 caffemodel,the python script is needed to import tensorflow,but I have never install tensorflow,so build failed.

yaml file:

```
library_name: squeezenet-v11
target_abis: [armeabi-v7a]
embed_model_data: 0
build_type: code
models:
  squeezenet_v11:
    platform: caffe
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/squeezenet/squeezenet-v1.1.prototxt
    weight_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/squeezenet/squeezenet-v1.1.caffemodel
    model_sha256_checksum: 625c952063da1569e22d2f499dc454952244d42cd8feca61f05502566e70ae1c
    weight_sha256_checksum: 72b912ace512e8621f8ff168a7d72af55910d3c7c9445af8dfbff4c2ee960142
    subgraphs:
      - input_tensors: data
        output_tensors: prob
        input_shapes: 1,227,227,3
        output_shapes: 1,1,1,1000
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

cmd:

```
bug1989@ubuntu:~/mace$ python tools/converter.py build --config=../mace-models/squeezenet/squeezenet-v11.yml
```

Terminal info:

```
bug1989@ubuntu:~/mace$ python tools/converter.py build --config=../mace-models/squeezenet/squeezenet-v11.yml 
------------------------------------
        Common Configuration        
------------------------------------
|       key       |     value      |
====================================
|     library_name|  squeezenet-v11|
------------------------------------
|      target_abis| ['armeabi-v7a']|
------------------------------------
|      target_socs|              []|
------------------------------------
|       build_type|            code|
------------------------------------
| embed_model_data|               0|
------------------------------------
|       linkshared|               0|
------------------------------------
|           Tuning|            True|
------------------------------------

* Genearte mace engine creator source
Genearte mace engine creator source done!

************************************************
          Convert squeezenet_v11 model          
************************************************

Downloading model, please wait ...
Model downloaded successfully.
INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 2.665s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

Traceback (most recent call last):
  File "/home/bug1989/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 22, in <module>
    from mace.python.tools import tf_dsp_converter_lib
  File "/home/bug1989/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/tf_dsp_converter_lib.py", line 17, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
Traceback (most recent call last):
  File "tools/converter.py", line 1386, in <module>
    flags.func(flags)
  File "tools/converter.py", line 902, in build_library
    convert_model(configs)
  File "tools/converter.py", line 667, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/bug1989/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/home/bug1989/.local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=caffe --model_file=build/squeezenet-v11/_tmp/squeezenet_v11/f71c295b8a511d160c6c3fadcb5537e1/model.pb --weight_file=build/squeezenet-v11/_tmp/squeezenet_v11/f71c295b8a511d160c6c3fadcb5537e1/model.caffemodel --model_checksum=625c952063da1569e22d2f499dc454952244d42cd8feca61f05502566e70ae1c --weight_checksum=72b912ace512e8621f8ff168a7d72af55910d3c7c9445af8dfbff4c2ee960142 --input_node=data --output_node=prob --runtime=cpu+gpu --template=mace/python/tools --model_tag=squeezenet_v11 --input_shape=1,227,227,3 --dsp_mode=0 --embed_model_data=0 --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/squeezenet_v11 --model_build_type=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:
```
