### ISSUE TITLE
关于量化时的输入尺度？

### ISSUE THREAD

**Issue by wincle** [XiaoMi/mace#297]
我注意到官方给的量化例子中，以及量化校验数据生成代码（tools/image/image_to_tensor.py），都是将输入数据归一化到 0～1，如果我的模型输入是0～255，该怎样调整呢？

**Comment by lee-bin** [comment]
1. 对于数据的预处理，可以按照特定模型修改image_to_tensor.py来转成tensor
2. 对于模型的输入范围，可以在yaml中设置input_ranges，例如
```
library_name: modelnet
target_abis: [armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  modelnet:
    platform: tensorflow
    model_file_path: xxx
    model_sha256_checksum: xxx
    subgraphs:
      - input_tensors: input
        output_tensors: Softmax
        input_shapes: 1,224,224,3
        output_shapes: 1,1001
        input_ranges: -0.5,0.5
    runtime: cpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0
    quantize: 1
```
