### ISSUE TITLE
Does Mace support Multi-task model ??? 

### ISSUE THREAD

**Issue by xmmxkk** [XiaoMi/mace#300]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:5.4.0
- **MACE version (Use the command: git describe --long --tags)**:1121
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.13.0

### Model deploy file (*.yml)
```yaml
library_name: mttask
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mttask:
    platform: caffe
    model_file_path: /verify_mace/dbn_deploy.prototxt
    weight_file_path: /verify_mace/dbn_deploy.caffemodel
    model_sha256_checksum: 9a0f18102987dc3963f7d1be769874d84fe16a7a3bb94d10e84683ea3167140d
    weight_sha256_checksum: c389fc1ae8d604216c5ff4cfdc3910e34c23a778093f4e18f1b994f6e5792f9b
    subgraphs:
        - input_tensors: data
        output_tensors: 
            - upscore8
            - conv20
            - conv21
        input_shapes: 
            - 1,320,320,3
        output_shapes: 
            - 1,320,320,4
            - 1,10,10,96
            - 1,20,20,96
    runtime: gpu 
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
    data_type: fp32_fp32
```

### Describe the problem
after convert the model in the yaml file above, the result of the output tensors is partly right with the same input, does mace support get multi-output at the same time for a forward computation??
1, Is the yaml file for deploy a multi output model right ?? althrough I have convert it successfully,but I am not sure.
2, I set "data" as input, any one of the three tensor "upscore8, conv20, conv21" as output tensor, i can get the right result after call the MaceEngine->Run?

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
