### ISSUE TITLE
小米6上在DSP中运行mobilenet-v1失败，Hexgon环境配置成功

### ISSUE THREAD

**Issue by newway1995** [XiaoMi/mace#318]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 18.04
- **NDK version(e.g., 15c)**: r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 7.3.0
- **MACE version (Use the command: git describe --long --tags)**:v0.10.0
- Deh
**Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.13.0
- **Client device information: MIUI10开发版 Xiaomi 6 (Rooted)** 

### Model deploy file (*.yml)
```yaml
library_name: mobilenet-v1-quantize-retrain-dsp
target_abis: [armeabi-v7a]
target_socs: [msm8998]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1_quantize_retrain:
    platform: tensorflow
    model_file_path: /Mace/models/pb/mobilenet_v1_1.0_224_quant_retrain.pb
    model_sha256_checksum: c3faa9bd790310eb3dec411d2f2e2dd8802394e31ccb47daaa5e3b6369fadfa3
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        input_ranges:
          - -1.0,1.0
        output_tensors:
          - MobilenetV1/Predictions/Softmax:0
        output_shapes:
          - 1,1001
        check_tensors:
          - MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0
        check_shapes:
          - 1,1,1,1001
        validation_inputs_data:
          - http://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/input_n01440764_15071.JPEG_input
    runtime: dsp
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
    quantize: 1

```

### Describe the problem
按照doc上面的要求已经配置好了HEXGON SDK以及需要的so库(https://github.com/XiaoMi/nnlib).  但是在小米6上面运行的时候报了错误，还是头文件对应的实现没有找到。是因为dsp现在只能在小米note3里面使用么？

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. update to the latest code  
3. python ./tools/converter.py run --config=./models/scripts/file/mobilenet-v1.yml 
```

### Error information / logs
```bash
* Build //mace/tools/validation:mace_run_static with ABI armeabi-v7a
INFO: Analysed target //mace/tools/validation:mace_run_static (0 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 0.191s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

******************************************************************
          Run model mobilenet_v1_quantize_retrain on MI6
******************************************************************

Generate input file:  builds/mobilenet-v1-quantize-retrain-dsp/_tmp/mobilenet_v1_quantize_retrain/43780a6dde814b4f53d4c432efbe093e/MI6_msm8998/armeabi-v7a/model_input_input
Generate input file done.
* Run 'mobilenet_v1_quantize_retrain' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/mobilenet-v1-quantize-retrain-dsp/_tmp/mobilenet_v1_quantize_retrain/43780a6dde814b4f53d4c432efbe093e/MI6_msm8998/armeabi-v7a/model_input_input to /data/local/tmp/mace_run
Push builds/mobilenet-v1-quantize-retrain-dsp/model/mobilenet_v1_quantize_retrain.data to /data/local/tmp/mace_run
Push third_party/nnlib/libhexagon_controller.so to /data/local/tmp/mace_run
Push builds/mobilenet-v1-quantize-retrain-dsp/model/mobilenet_v1_quantize_retrain.pb to /data/local/tmp/mace_run/mobilenet_v1_quantize_retrain.pb
Push builds/mobilenet-v1-quantize-retrain-dsp/_tmp/armeabi-v7a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-mobilenet_v1_quantize_retrain-1548029678.35 to /data/local/tmp/mace_run/cmd_file-mobilenet_v1_quantize_retrain-1548029678.35
WARNING: linker: Warning: unable to normalize "external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/5.0.300080/lib/linux/arm"
I mace_run.cc:586 model name: mobilenet_v1_quantize_retrain
I mace_run.cc:587 mace version: v0.10.0-1-ge0172d23-20190104
I mace_run.cc:588 input node: input
I mace_run.cc:589 input shape: 1,224,224,3
I mace_run.cc:590 output node: MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0
I mace_run.cc:591 output shape: 1,1,1,1001
I mace_run.cc:592 input_file: /data/local/tmp/mace_run/model_input
I mace_run.cc:593 output_file: /data/local/tmp/mace_run/model_out
I mace_run.cc:594 model_data_file: /data/local/tmp/mace_run/mobilenet_v1_quantize_retrain.data
I mace_run.cc:595 model_file: /data/local/tmp/mace_run/mobilenet_v1_quantize_retrain.pb
I mace_run.cc:596 device: HEXAGON
I mace_run.cc:597 round: 1
I mace_run.cc:598 restart_round: 1
I mace_run.cc:599 gpu_perf_hint: 3
I mace_run.cc:600 gpu_priority_hint: 3
I mace_run.cc:601 omp_num_threads: -1
I mace_run.cc:602 cpu_affinity_policy: 1
I mace_run.cc:625 restart round 0
I mace.cc:783 Create MaceEngine from model pb
I mace.cc:391 Creating MaceEngine, MACE version: v0.10.0-1-ge0172d23-20190104
I mace.cc:506 Loading Model Data
I mace.cc:509 Tensor size: 254, operation size: 31
I mace.cc:423 Initializing MaceEngine
I hexagon_control_wrapper.cc:102 Hexagon config
F hexagon_control_wrapper.cc:103 Check failed: hexagon_nn_set_powersave_level(0) == 0 hexagon power error
Aborted
Traceback (most recent call last):
  File "./tools/converter.py", line 1248, in <module>
    flags.func(flags)
  File "./tools/converter.py", line 967, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/tools/device.py", line 563, in run_specify_abi
    output_dir=flags.output_dir,
  File "/tools/device.py", line 332, in tuning_run
    _err_to_out=True)
  File "/tools/device.py", line 69, in exec_command
    sh.adb('-s', self.address, 'shell', command, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_134:

  RAN: /Users/newway/Library/Android/sdk/platform-tools/adb -s e1a5f5c0 shell sh /data/local/tmp/mace_run/cmd_file-mobilenet_v1_quantize_retrain-1548029678.35

  STDOUT:


  STDERR:
```
