### ISSUE TITLE
tensorflow pb模型Similarity Test Failed

### ISSUE THREAD

**Issue by wayen820** [XiaoMi/mace#363]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:18
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:v0.10.0-0-g22e40d6-20190220
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```
library_name: ssd_prnet
target_abis: [arm64-v8a]
#target_socs: [sdm845]
model_graph_format: code
model_data_format: code
models:
  sprnet:
    platform: tensorflow
    model_file_path: /Net_loss0.0173_4channeloutput_use_first3.pb
    model_sha256_checksum: 2e8517dfe37ec8717550409881a4dd7723b53038ac38b2c80dda5b33b8d5966f
    subgraphs:
      - input_tensors:
          - input_1
        input_shapes:
          - 1,256,256,3
        output_tensors:
          - upconv6_4/convolution
        output_shapes:
          - 1,256,256,4
    runtime: gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 4

```

### Describe the problem
我这个模型用gpu跑，发现validate失败，我一层一层找，发现失败就在最后一层conv的这个操作，输入conv之前都是对的，从这个conv出来后就不对了，导致最终输出也不对。但是我用cpu来跑却是对的。pb模型我放在 https://share.weiyun.com/5pmlGSc 

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
2. python tools/converter.py run --config_file=/path/to/your/model_deployment_file --validate
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
* Validate with tensorflow
Pull /data/local/tmp/mace_run to builds/ssd_prnet/_tmp/sprnet/0be70f3cff2c2355c100cb8a4b5e59fb/MI8_sdm845/arm64-v8a
/media/wayen/DATA/work/mace/mace/tools/validate.py:66: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
upconv6_4/convolution MACE VS TENSORFLOW similarity: nan , sqnr: 1.0 , pixel_accuracy: 0.113845825195
ERROR: [] ******************************************
          Similarity Test Failed          
******************************************

```
