### ISSUE TITLE
Quantized model cannot run

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#364]
I'm running MACE using the provided docker image.

### Model deploy file (*.yml)
```
library_name: test
target_abis: [armeabi-v7a]
target_socs: [sdm845]
model_graph_format: file
model_data_format: file
models:
  test:
    model_file_path: /model/frozen_model.pb
    model_sha256_checksum: 77d382efd2a88f9ee5b23fcd71a4888d37daf914205adc0176c25d3245c7f26e
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,112,112,3
        output_tensors:
          - fc1/add_1
        output_shapes:
          - 1,1,1,512
    obfuscate: 0
    quantize: 1
    runtime: cpu+gpu # cpu, gpu or cpu+gpu or dsp
    winograd: 0
```

### Describe the problem
I've successfully converted my model to a quantized version, but it cannot run on the device.

### Error information / logs
When running on CPU:
```bash
I mace.cc:739 Create MaceEngine from model pb
I mace.cc:390 Creating MaceEngine, MACE version: v0.10.0-0-g22e40d6-20190220
I mace.cc:501 Loading Model Data
I mace.cc:422 Initializing MaceEngine
F operator.cc:272 Key not registered: Pad0T_DT_UINT8
Aborted 
```

When running on GPU:
```bash
W tuner.h:142 Read OpenCL tuned parameters file failed.
I mace.cc:739 Create MaceEngine from model pb
I mace.cc:390 Creating MaceEngine, MACE version: v0.10.0-0-g22e40d6-20190220
I mace.cc:501 Loading Model Data
I mace.cc:422 Initializing MaceEngine
F operator.cc:272 Key not registered: BufferTransform2T_DT_UINT8
Aborted 
```
