### ISSUE TITLE
Error DSP conversion

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#381]
I'm working with the provided Docker image, that means:
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.5 LTS
- **NDK version(e.g., 15c)**: 15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0-0-g22e40d6
- **Python version(2.7)**: 2.7.14
- **Bazel version (e.g., 0.13.0)**: 0.16.0

### Model deploy file (*.yml)
```yaml
library_name: model_test
target_abis: [armeabi-v7a]
target_socs: [sdm845]
model_graph_format: file
model_data_format: file
models:
  model:
    platform: tensorflow
    model_file_path: /model/frozen_model.pb
    model_sha256_checksum: 77d382efd2a88f9ee5b23fcd71a4888d37daf914205adc0176c25d3245c7f26e
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,112,112,3
        output_tensors:
          - fc/add
        output_shapes:
          - 1,1,1,512
    obfuscate: 0
    quantize: 1
    quantize_range_file: /mace/overall_range
    runtime: dsp
    winograd: 0
```

### Describe the problem
When trying to convert to DSP with quantization, conversion fails due to wrong input tensor name.
MaceCheck fails because generated inputs to Op Add are named mace_input_data:0 and mace_input_data:1

### To Reproduce
Steps to reproduce the problem (after having obtained the quantization stats and logs):
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
<pre>
Convert mace graph to hexagon.
Op: mace_input_node_data (Quantize)
Op: Add (Eltwise)
Traceback (most recent call last):
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 355, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 202, in main
    output_graph_def = converter.run()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/hexagon_converter.py", line 100, in run
    self.convert_ops()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/hexagon_converter.py", line 161, in convert_ops
    self.add_min_max_const_node(op, op.input[1])
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/hexagon_converter.py", line 277, in add_min_max_const_node
    mace_check(port == 0, 'port should be 0 to add min max tensor then.')
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: <b>port should be 0 to add min max tensor then.</b>
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 761, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 691, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mace/tools/sh_commands.py", line 518, in gen_model_code
    _fg=True)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /root/.pyenv/versions/2.7.14/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/model/frozen_model.pb --weight_file= --model_checksum=77d382efd2a88f9ee5b23fcd71a4888d37daf914205adc0176c25d3245c7f26e --weight_checksum= --input_node=data --input_data_formats=NHWC --output_node=fc/add --output_data_formats=NHWC --check_node= --runtime=dsp --template=mace/python/tools --model_tag=model --input_shape=1,112,112,3 --input_range= --output_shape=1,1,1,512 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=1 --quantize_range_file=/mace/overall_range --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/model --model_graph_format=file --data_type=uint8 --graph_optimize_options= --cl_mem_type=image

  STDOUT:

  STDERR:
</pre>

### Additional context
If I try to print the tensors responsible for the error, this is the result:

```
Op: mace_input_node_data (Quantize)
Op: Add (Eltwise)
tensor0: mace_input_node_data:0
tensor1: mace_input_node_data:1
```

And if I try to bypass the MACECHECK throwing the error, then I get:

```
Exception: ('Quantize info not found: ', u'mace_input_node_data:1')
```
