### ISSUE TITLE
MACE model output not consistent

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#405]
I'm working with the provided Docker image, that means:
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.5 LTS
- **NDK version(e.g., 15c)**: 15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0-0-g22e40d6
- **Python version(2.7)**: 2.7.14
- **Bazel version (e.g., 0.13.0)**: 0.16.0

### Model deploy file (*.yml)
```yaml
library_name: model_test
target_abis: [host]
model_graph_format: file
model_data_format: file
models:
  model:
    platform: tensorflow
    model_file_path: /model/frozen_model.pb
    model_sha256_checksum: 77d382efd2a88f9ee5b23fcd71a4888d37daf914205adc0176c25d3245c7f26e
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,112,112,3
        output_tensors:
          - fc/add
        output_shapes:
          - 1,1,1,512
    obfuscate: 0
    runtime: cpu
    winograd: 0
```

### Describe the problem
Model runs and produces output, but the output is not consistent with the original model one. Even though when running with `--validate` it shows a very high similarity with original model, the output similarity (compared with an external script) between MACE model output and original model one is between 0.6-0.7.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
3. python tools/converter.py run --config_file=/path/to/your/model_deployment_file --validate
4. compare results with original ones using external comparison script
```

### Additional context
Pre-processing and post processing of the input/output files are exactly the same in both pipelines. I also tested in the same way other optimized models (TFLite, SNPE, etc..) outputs and the similarity with the original ones is always extremely close to 1.
