### ISSUE TITLE
配置文件中的输入宽度大于512时，运行就报错

### ISSUE THREAD

**Issue by junjin8433** [XiaoMi/mace#422]
### System information
官方Docker下转换的模型，安卓下调用

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: ocr_recognize
target_abis: [arm64-v8a]
#target_socs: [sdm845]
model_graph_format: file 
model_data_format: file 
models:
  ocr_recognize: # model tag, which will be used in model loading and must be specific.
    platform: tensorflow
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /home/Documents/my_model/ocr_recognize/ocr_recognize.pb
    # sha256_checksum of your model's pb file.
    # use this command to get the sha256_checksum: sha256sum path/to/your/pb/file
    model_sha256_checksum: b0813900ac1011d76a65f90752a611a700503f1e9f6854c664fa885e81d0696f 
    subgraphs:
      - input_tensors:
          - input_node/images:0
        input_shapes:
          - 1,512,1024,3
        output_tensors:
          - mobilenetv2/output/cls:0
          - mobilenetv2/output/num:0
        output_shapes:
          - 1,64,128,38
          - 1,64,128,2
    # cpu, gpu or cpu+gpu
    runtime: cpu+gpu
    winograd: 0

```

### Describe the problem
一旦转换时候yaml文件中设置的输入宽度（高度没事）大于512，无论实际输入的尺寸多大，都报如下错误：
![image](https://user-images.githubusercontent.com/15881885/55697490-2e963900-59f4-11e9-9548-685ccdbad109.png)
A/MACE: operator.h:140 Check failed: idx < inputs_.size()

### 附上PB文件
[ocr_recognize.pb.zip](https://github.com/XiaoMi/mace/files/3052554/ocr_recognize.pb.zip)
