### ISSUE TITLE
caffe to mace

### ISSUE THREAD

**Issue by chenloveheimei** [XiaoMi/mace#425]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution Ubuntu 16.04**:
- **NDK version 16r**:
- **GCC version(5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (0.15.0)**:

### Model deploy file (*.yml)
````````
library_name: cpmCaffe
target_abis: [armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  openposecaffe: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    # support local path, http:// and https://
    model_file_path: /media/long/data/android/PoseEstimationForMobile/caffemodel/new.prototxt 
    weight_file_path: /media/long/data/android/PoseEstimationForMobile/caffemodel/new.caffemodel
    # sha256_checksum of your model's graph and data files.
    # get the sha256_checksum: sha256sum path/to/your/file
    model_sha256_checksum: 9b335cbfb0acefe8d64237bda267180ec2fdfb24005386c99f01daa4bacf25e6
    weight_sha256_checksum: 6b382bcf12e75b51e635d166b909301c499debfefa4cb1ebf8f9a7c2ee1137cc
    # define your model's interface
    # if there multiple inputs or outputs, write like blow:
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,128,128,3
        output_tensors:
          - detection_out
        output_shapes:
          - 1,1,1,6
    runtime: cpu+gpu
    winograd: 0
````

### Describe the problem
A clear and concise description of what the bug is.

### To Reproduce
Steps to reproduce the problem:
```bash
python tools/converter.py convert --config=/media/long/data/android/PoseEstimationForMobile/release/mace_ymls/cpmCaffe.yml 
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
![image](https://user-images.githubusercontent.com/30176962/56037277-77861e80-5d61-11e9-92e0-45fea5a972d1.png)

picture ,check the website.
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
