### ISSUE TITLE
关于mace_model里面ssd-mobilenet-v1几个问题

### ISSUE THREAD

**Issue by chenloveheimei** [XiaoMi/mace#432]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu16.04
- **NDK version(e.g., 15c)**:
NDK r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
gcc 5.4.0
- **MACE version (Use the command: git describe --long --tags)**:
mace v0.10.0-0-g22e40d6
- **Python version(2.7)**: 
python 2.7
- **Bazel version (e.g., 0.13.0)**:
bazel 0.13.0

### Model deploy file (*.yml)
```yaml
Name:ssd-mobilenet-v1_caffe.yml

library_name: ssd-mobilenet-v1
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  ssd_mobilenet_v1:
    platform: caffe
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/ssd-mobilenet-v1/MobileNetSSD_deploy_new.prototxt
    weight_file_path: http://cnbj1.fds.api.xiaomi.com/mace/miai-models/ssd-mobilenet-v1/MobileNetSSD_deploy_new.caffemodel
    model_sha256_checksum: ed517e22400248542814f258c125b0921483170cd7b482a63f1cdae5e36fa636
    weight_sha256_checksum: 761c86fbae3d8361dd454f7c740a964f62975ed32f4324b8b85994edec30f6af
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,300,300,3
        output_tensors:
          - mbox_loc
          - mbox_conf_flatten
          - mbox_priorbox
        output_shapes:
          - 1,7668
          - 1,40257
          - 1,2,7668
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/cat300.npy
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
    docker_image_tag: ssd
    dockerfile_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/ssd-mobilenet-v1/Dockerfile
    dockerfile_sha256_checksum: 3cdd6c526937cf92f3aad0e6b66cbbe62f3a71f7883af1020b1f3f9267c80f9e
......
```

### **_问题1:_**
如果不修改yml里面的输出维度,他会报错维度出错,所以,我会把维度修改为如下:
input_tensors:
          - data
input_shapes:
          - 1,300,300,3
output_tensors:
          - mbox_loc
          - mbox_conf_flatten
          - mbox_priorbox
output_shapes:
          - 1,1,1,7668
          - 1,40257,1
          - 1,2,7668
所以这个问题是否有必要改呢?

### **_问题2:_**
我修改了yml的输出维度之后,把生成的.so和.h都拉到android demo里面,运行demo里面的CPU模式,是可以成功把项目安装到手机里并且能正常打开.但是我改成GPU模式,就报错,报错log如下:
2019-04-28 10:22:34.375 29310-29536/pacificfuture.humanpose A/MACE: concat.cc:92 Check failed: input->dim(j) == input0->dim(j) Dimensions of inputs should equal except axis.
2019-04-28 10:22:34.511 29591-29591/? A/DEBUG:     #01 pc 000000000025a370  /data/app/pacificfuture.humanpose-HoNkWg7uEvCtrfURICp7xw==/lib/arm64/libmace.so (mace::logging::LogMessage::GenerateLogMessage()+976)
2019-04-28 10:22:34.511 29591-29591/? A/DEBUG:     #02 pc 000000000025a5b8  /data/app/pacificfuture.humanpose-HoNkWg7uEvCtrfURICp7xw==/lib/arm64/libmace.so (mace::logging::LogMessage::~LogMessage()+144)
2019-04-28 10:22:34.511 29591-29591/? A/DEBUG:     #03 pc 000000000025a6ac  /data/app/pacificfuture.humanpose-HoNkWg7uEvCtrfURICp7xw==/lib/arm64/libmace.so (mace::logging::LogMessage::~LogMessage()+24)
2019-04-28 10:22:34.511 29591-29591/? A/DEBUG:     #04 pc 000000000009e7c4  /data/app/pacificfuture.humanpose-HoNkWg7uEvCtrfURICp7xw==/lib/arm64/libmace.so
2019-04-28 10:22:34.511 29591-29591/? A/DEBUG:     #05 pc 00000000001f88e0  /data/app/pacificfuture.humanpose-HoNkWg7uEvCtrfURICp7xw==/lib/arm64/libmace.so
2019-04-28 10:22:34.511 29591-29591/? A/DEBUG:     #06 pc 0000000000059920  /data/app/pacificfuture.humanpose-HoNkWg7uEvCtrfURICp7xw==/lib/arm64/libmace.so (_ZN4mace10MaceEngine4Impl3RunERKSt3mapISsNS_10MaceTensorESt4lessISsESaISt4pairIKSsS3_EEEPSA_PNS_11RunMetadataE+1724)
2019-04-28 10:22:34.511 29591-29591/? A/DEBUG:     #08 pc 0000000000045258  /data/app/pacificfuture.humanpose-HoNkWg7uEvCtrfURICp7xw==/lib/arm64/libnative-lib.so (Java_pacificfuture_humanpose_MainActivity_maceMobilenetClassify+48)

### **_问题3:_**
我在CPU模式下,想输出detectionoutput,我使用了你们里面的detection_output.cc里面的DetectionOutput,但是输出的值,我不知道代表什么,我的写法如下:
struct ModelInfo {
    std::string input_name;
    std::string output_name;
    std::string output_name1;
    std::string output_name2;
    std::vector<int64_t> input_shape;
    std::vector<int64_t> output_shape;
    std::vector<int64_t> output_shape1;
    std::vector<int64_t> output_shape2;
};

struct MaceContext {
    std::shared_ptr<mace::GPUContext> gpu_context;
    std::shared_ptr<mace::MaceEngine> engine;
    std::string model_name;
    mace::DeviceType device_type = mace::DeviceType::CPU;
    std::map<std::string, ModelInfo> model_infos = {
            {"ssd_mobilenet_v1", {"data", "mbox_loc", "mbox_conf_flatten","mbox_priorbox",
                                     {1,300,300,3}, {1,1,1,7668}, {1,40257,1}, {1,2,7668}}}
    };
};

const int num_prior = 1692;
const int num_classes =21;
const float nms_threshold =0.45;
const int top_k =100;
const int keep_top_k =100;
const float confidence_threshold =0.25;
std::vector<BBox> bbox_rects;

int detectionNum=DetectionOutput(outputs["mbox_loc"].data().get(),outputs["mbox_conf_flatten"].data().get(),outputs["mbox_priorbox"].data().get(),
                                       num_prior,
                                       num_classes,
                                       nms_threshold,
                                       top_k,
                                       keep_top_k,
                                       confidence_threshold,
                                       &bbox_rects);

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
