### ISSUE TITLE
Mace fails to load const tensor for GPU inference

### ISSUE THREAD

**Issue by sumant85** [XiaoMi/mace#458]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.6
- **NDK version(e.g., 15c)**: r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 
- **MACE version (Use the command: git describe --long --tags)**: v0.11.0-rc0-69-g304aea36
- **Python version(2.7)**:  2.7
- **Bazel version (e.g., 0.13.0)**: 0.20.0-homebrew

### Model deploy file (*.yml)
```yaml
library_name: mace_concat
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mace_concat:
    platform: tensorflow
    model_file_path: /root/mace_concat.pb
    model_sha256_checksum: cc824e43368eb7f605108e831aa072c3dfed0d778cfd4fea4bc054351fcc5509
    subgraphs:
      - input_tensors:
          - image:0
        input_shapes:
          - 1,1,1,32
        output_tensors:
          - add/output
        output_shapes:
          - 1,1,1,64
    runtime: gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

### Model Link
[mace_concat.zip](https://github.com/XiaoMi/mace/files/3264008/mace_concat.pb.zip)

### Describe the problem
- We would like to pass a pre-computed tensor to mace and concat it with the output of an intermediate node in the network.
- We tried the attached model, but it fails to run on GPU.

### To Reproduce
Just run the attached model with MACE helper scripts.

### Error information
Fails in  https://github.com/XiaoMi/mace/blob/master/mace/core/tensor.h#L243
```
`I mace/tools/validation/mace_run.cc:315] Warm up run
F ./mace/core/tensor.h:243] Check failed: has_opencl_image() add/const:0 do not have image
F ./mace/core/tensor.h:243] backtrace:
F ./mace/core/tensor.h:243]  pc 0x31da0db78
F ./mace/core/tensor.h:243]  pc 0x31da10eb4
F ./mace/core/tensor.h:243]  pc 0x31da10df0
F ./mace/core/tensor.h:243]  pc 0x31da11330
F ./mace/core/tensor.h:243]  pc 0x31da11440
F ./mace/core/tensor.h:243]  pc 0x31d96aafc
F ./mace/core/tensor.h:243]  pc 0x31d9766b8
F ./mace/core/tensor.h:243]  pc 0x31d9793b0
F ./mace/core/tensor.h:243]  pc 0x31d9c1364
F ./mace/core/tensor.h:243]  pc 0x31d88cb5c
F ./mace/core/tensor.h:243]  pc 0x31d869644
F ./mace/core/tensor.h:243]  pc 0x31d86bf98
F ./mace/core/tensor.h:243]  pc 0x31d86cafc
F ./mace/core/tensor.h:243]  pc 0x7a42373b04 __libc_init
F ./mace/core/tensor.h:243]  pc 0x31d867db4
Aborted
ERROR: [Mace Run] /root/armnn-devenv/mace/tools/device.py:362: Mace run failed.`
```
