### ISSUE TITLE
华为 CHE-TL00H Android 5.0.2 fp32/activation.cc 出现crash

### ISSUE THREAD

**Issue by TChallaLiu** [XiaoMi/mace#498]
### Model deploy file (*.yml)
```yaml
library_name: classify
target_abis: [armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  classify:
    platform: onnx
    model_file_path: /Users/canyaoliu/code/ai/mace/wspd-model-zoo/scene/classify_20190723/classify_opt.onnx
    model_sha256_checksum: 019eb348fc78d351c4fe036485269d5d0f3c1638355bdf7a37e2e6f13b2cd19e
    subgraphs:
      - input_tensors:
          - 0
        input_shapes:
          - 1,3,224,224
        input_data_formats:
          - NCHW
        output_tensors:
          - 468
        output_shapes:
          - 1,41,1,1
        output_data_formats:
          - NCHW
        backend: pytorch
    runtime: gpu
    winograd: 0

```

### 问题描述
华为 畅玩 4x CHE-TL00H Android OS 5.0.2 运行到 fp32/activation.cc出现crash

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
3.python tools/converter.py run --config=/Users/canyaoliu/code/ai/mace/model-zoo/scene/classify_20190723/classify.yml  --debug_mode
4.adb logcat | $ANDROID_NDK_HOME/ndk-stack -sym /Users/canyaoliu/code/ai/mace/mace/builds/classify/_tmp/armeabi-v7a

```

### converter.py run --debug_model log
```bash
* Build //mace/tools/validation:mace_run_static with ABI armeabi-v7a
WARNING: ignoring http_proxy in environment.
INFO: Analysed target //mace/tools/validation:mace_run_static (1 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 1.866s, Critical Path: 0.04s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

***************************************************
          Run model classify on CHE-TL00H          
***************************************************

Generate input file:  builds/classify/_tmp/classify/ecb50bc23f1b47ce361dde5eb4d03dd1/CHE-TL00H_hi6210sft/armeabi-v7a/model_input_0
Generate input file done.
* Run 'classify' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/classify/_tmp/classify/ecb50bc23f1b47ce361dde5eb4d03dd1/CHE-TL00H_hi6210sft/armeabi-v7a/model_input_0 to /data/local/tmp/mace_run
Push builds/classify/model/classify.data to /data/local/tmp/mace_run
Push builds/classify/model/classify.pb to /data/local/tmp/mace_run/classify.pb
Push builds/classify/_tmp/armeabi-v7a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-classify-1564125901.092724 to /data/local/tmp/mace_run/cmd_file-classify-1564125901.092724
I mace/tools/validation/mace_run.cc:449] model name: classify
I mace/tools/validation/mace_run.cc:450] mace version: v0.10.0-273-g516014ed
I mace/tools/validation/mace_run.cc:451] input node: 0
I mace/tools/validation/mace_run.cc:452] input shape: 1,3,224,224
I mace/tools/validation/mace_run.cc:453] output node: 468
I mace/tools/validation/mace_run.cc:454] output shape: 1,41,1,1
I mace/tools/validation/mace_run.cc:455] input_file: /data/local/tmp/mace_run/model_input
I mace/tools/validation/mace_run.cc:456] output_file: /data/local/tmp/mace_run/model_out
I mace/tools/validation/mace_run.cc:457] model_data_file: /data/local/tmp/mace_run/classify.data
I mace/tools/validation/mace_run.cc:458] model_file: /data/local/tmp/mace_run/classify.pb
I mace/tools/validation/mace_run.cc:459] device: GPU
I mace/tools/validation/mace_run.cc:460] round: 1
I mace/tools/validation/mace_run.cc:461] restart_round: 1
I mace/tools/validation/mace_run.cc:462] gpu_perf_hint: 3
I mace/tools/validation/mace_run.cc:463] gpu_priority_hint: 3
I mace/tools/validation/mace_run.cc:464] omp_num_threads: -1
I mace/tools/validation/mace_run.cc:465] cpu_affinity_policy: 1
E mace/port/linux_base/env.cc:86] failed to open /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq
I mace/port/android/env.cc:97] LinuxBaseEnv::GetCPUMaxFreq(max_freqs) failed with error: Runtime error
E mace/utils/thread_pool.cc:140] Fail to get cpu max frequencies
I mace/libmace/mace.cc:419] Creating MaceEngine, MACE version: v0.10.0-273-g516014ed
E mace/port/linux_base/env.cc:86] failed to open /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq
I mace/port/android/env.cc:97] LinuxBaseEnv::GetCPUMaxFreq(max_freqs) failed with error: Runtime error
I mace/core/runtime/cpu/cpu_runtime.cc:99] GetCPUMaxFreq(&cpu_max_freqs) failed with error: Runtime error
I mace/libmace/mace.cc:453] Initializing MaceEngine
E mace/port/linux_base/env.cc:86] failed to open /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq
I mace/port/android/env.cc:97] LinuxBaseEnv::GetCPUMaxFreq(max_freqs) failed with error: Runtime error
I mace/core/runtime/cpu/cpu_runtime.cc:99] GetCPUMaxFreq(&cpu_max_freqs) failed with error: Runtime error
E mace/port/linux_base/env.cc:86] failed to open /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq
I mace/port/android/env.cc:97] LinuxBaseEnv::GetCPUMaxFreq(max_freqs) failed with error: Runtime error
I mace/core/runtime/cpu/cpu_runtime.cc:99] GetCPUMaxFreq(&cpu_max_freqs) failed with error: Runtime error
Bus error
Running finished!

Elapse time: 2.030642 minutes.
* Package libs for classify
Start packaging 'classify' libs into builds/classify/libmace_classify.tar.gz
a builds/classify/model
a builds/classify/model/classify.pb
a builds/classify/model/classify.data
Packaging Done!

-------------------------------------------------------------------
                              Library                              
-------------------------------------------------------------------
|          key           |                 value                  |
===================================================================
| MACE Model package Path| builds/classify/libmace_classify.tar.gz|
-------------------------------------------------------------------

```

### adb logcat | $ANDROID_NDK_HOME/ndk-stack -sym log
```bash
********** Crash dump: **********
Build fingerprint: 'Honor/CHE-TL00H/hnCHE-H:5.0.2/HonorCHE-TL00H/C00B210:user/release-keys'
pid: 16194, tid: 16196, name: mace_run_static  >>> /data/local/tmp/mace_run/mace_run_static <<<
signal 7 (SIGBUS), code 0 (SI_USER), fault addr 0xab3bbe58
Stack frame #00 pc 00208cc0  /data/local/tmp/mace_run/mace_run_static: Routine operator() at /private/var/tmp/_bazel_canyaoliu/35217bea15c94c19062bea349991c1e6/sandbox/8266038678114721738/execroot/mace/mace/ops/arm/fp32/activation.cc:98
Stack frame #01 pc 00000000  <unknown>
Crash dump is completed

```
