### ISSUE TITLE
Fallback to CPU much slower than native CPU execution

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#519]
I'm using the provided docker image with MACE v0.10.0

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: mnet
target_abis: [host]
model_graph_format: file
model_data_format: file
models:
  mnet_model: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    model_file_path: /models/mnet.prototxt
    weight_file_path: /models/mnet.caffemodel
    model_sha256_checksum: 60814a424f5195ffe3ad9193dbe5123113603e7fa6f30b1b8266b63f2d72bf24
    weight_sha256_checksum: 09d1e6950af1df233b3d323e9e971a7fa5d391a22ba679252cc6a22d92cdb06a
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,640,640
        output_tensors:
          - face_rpn_cls_prob_reshape_stride32
          - face_rpn_bbox_pred_stride32
          - face_rpn_landmark_pred_stride32
          - face_rpn_cls_prob_reshape_stride16
          - face_rpn_bbox_pred_stride16
          - face_rpn_landmark_pred_stride16
          - face_rpn_cls_prob_reshape_stride8
          - face_rpn_bbox_pred_stride8
          - face_rpn_landmark_pred_stride8
        output_shapes:
          - 1,4
          - 1,8
          - 1,20
          - 1,4
          - 1,8
          - 1,20
          - 1,4
          - 1,8
          - 1,20
    obfuscate: 0
    runtime: cpu # cpu, gpu or cpu+gpu or dsp
    winograd: 0
```

### Describe the problem
I'm benchmarking my model on different targets (CPU, GPU, etc).
When running the model on GPU, some ops fall back to CPU, but the time taken is extremely longer than the time required for the same operation when it is executed natively on CPU.
In my case the ops falling back are `reshape` and `softmax`. Especially `softmax` definitely has a huge impact on the total time of GPU run.
Please see the logs below for an example.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
2. python tools/converter.py benchmark --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.

On GPU:
```bash
I mace/benchmark/statistics.cc:347] 
I mace/benchmark/statistics.cc:347] -------------------------------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347]                                         Stat by Op Type
I mace/benchmark/statistics.cc:347] -------------------------------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] |           Op Type | Count | Avg(ms) |      % |    cdf% |        MACs |  GMACPS | Called times |
I mace/benchmark/statistics.cc:347] -------------------------------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] |           Softmax |     3 |  11.898 | 47.939 |  47.939 |           0 |   0.000 |            3 |
I mace/benchmark/statistics.cc:347] |            Conv2D |    43 |   7.219 | 29.087 |  77.026 | 945,664,000 | 130.997 |           43 |
I mace/benchmark/statistics.cc:347] |   DepthwiseConv2d |    13 |   2.262 |  9.114 |  86.140 |  35,481,600 |  15.686 |           13 |
I mace/benchmark/statistics.cc:347] |           Reshape |     6 |   1.667 |  6.717 |  92.856 |           0 |   0.000 |            6 |
I mace/benchmark/statistics.cc:347] |   BufferTransform |    10 |   0.667 |  2.687 |  95.544 |           0 |   0.000 |           10 |
I mace/benchmark/statistics.cc:347] |         Transpose |     3 |   0.564 |  2.272 |  97.816 |           0 |   0.000 |            3 |
I mace/benchmark/statistics.cc:347] |            Concat |     3 |   0.144 |  0.580 |  98.396 |           0 |   0.000 |            3 |
I mace/benchmark/statistics.cc:347] |           Eltwise |     2 |   0.125 |  0.504 |  98.900 |           0 |   0.000 |            2 |
I mace/benchmark/statistics.cc:347] |        Activation |     3 |   0.101 |  0.407 |  99.307 |           0 |   0.000 |            3 |
I mace/benchmark/statistics.cc:347] | DepthwiseDeconv2d |     2 |   0.089 |  0.359 |  99.666 |   2,048,000 |  23.011 |            2 |
I mace/benchmark/statistics.cc:347] |              Crop |     2 |   0.083 |  0.334 | 100.000 |           0 |   0.000 |            2 |
I mace/benchmark/statistics.cc:347] -------------------------------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] 
I mace/benchmark/statistics.cc:347] ----------------------------------------------------------
I mace/benchmark/statistics.cc:347]            Stat by MACs(Multiply-Accumulation)
I mace/benchmark/statistics.cc:347] ----------------------------------------------------------
I mace/benchmark/statistics.cc:347] |       total | round | first(G/s) | avg(G/s) |      std |
I mace/benchmark/statistics.cc:347] ----------------------------------------------------------
I mace/benchmark/statistics.cc:347] | 983,193,600 |    65 |     36.003 |   39.542 | 2587.510 |
I mace/benchmark/statistics.cc:347] ----------------------------------------------------------
I mace/benchmark/statistics.cc:347] -------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347]                           Summary of Ops' Stat
I mace/benchmark/statistics.cc:347] -------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] | round | first(ms) | curr(ms) | min(ms) | max(ms) | avg(ms) |      std |
I mace/benchmark/statistics.cc:347] -------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] |    65 |    27.309 |   22.272 |  19.966 |  31.873 |  24.864 | 2587.510 |
I mace/benchmark/statistics.cc:347] -------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] 
I mace/benchmark/statistics.cc:347] 90 ops total.
I mace/libmace/mace.cc:603] Destroying MaceEngine
Benchmark done! 
```

On CPU:
```bash
I mace/benchmark/statistics.cc:347] 
I mace/benchmark/statistics.cc:347] ------------------------------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347]                                         Stat by Op Type
I mace/benchmark/statistics.cc:347] ------------------------------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] |           Op Type | Count | Avg(ms) |      % |    cdf% |        MACs | GMACPS | Called times |
I mace/benchmark/statistics.cc:347] ------------------------------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] |            Conv2D |    43 |  33.638 | 85.200 |  85.200 | 945,664,000 | 28.113 |           43 |
I mace/benchmark/statistics.cc:347] |   DepthwiseConv2d |    13 |   4.653 | 11.785 |  96.986 |  35,481,600 |  7.626 |           13 |
I mace/benchmark/statistics.cc:347] | DepthwiseDeconv2d |     2 |   0.276 |  0.699 |  97.685 |   2,048,000 |  7.420 |            2 |
I mace/benchmark/statistics.cc:347] |              Crop |     2 |   0.267 |  0.676 |  98.361 |           0 |  0.000 |            2 |
I mace/benchmark/statistics.cc:347] |            Concat |     3 |   0.202 |  0.512 |  98.873 |           0 |  0.000 |            3 |
I mace/benchmark/statistics.cc:347] |           Eltwise |     2 |   0.196 |  0.496 |  99.369 |           0 |  0.000 |            2 |
I mace/benchmark/statistics.cc:347] |        Activation |     3 |   0.125 |  0.317 |  99.686 |           0 |  0.000 |            3 |
I mace/benchmark/statistics.cc:347] |           Softmax |     3 |   0.116 |  0.294 |  99.980 |           0 |  0.000 |            3 |
I mace/benchmark/statistics.cc:347] |           Reshape |     6 |   0.008 |  0.020 | 100.000 |           0 |  0.000 |            6 |
I mace/benchmark/statistics.cc:347] ------------------------------------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] 
I mace/benchmark/statistics.cc:347] --------------------------------------------------------
I mace/benchmark/statistics.cc:347]           Stat by MACs(Multiply-Accumulation)
I mace/benchmark/statistics.cc:347] --------------------------------------------------------
I mace/benchmark/statistics.cc:347] |       total | round | first(G/s) | avg(G/s) |    std |
I mace/benchmark/statistics.cc:347] --------------------------------------------------------
I mace/benchmark/statistics.cc:347] | 983,193,600 |   100 |     24.851 |   24.879 | 86.377 |
I mace/benchmark/statistics.cc:347] --------------------------------------------------------
I mace/benchmark/statistics.cc:347] -----------------------------------------------------------------------
I mace/benchmark/statistics.cc:347]                          Summary of Ops' Stat
I mace/benchmark/statistics.cc:347] -----------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] | round | first(ms) | curr(ms) | min(ms) | max(ms) | avg(ms) |    std |
I mace/benchmark/statistics.cc:347] -----------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] |   100 |    39.564 |   39.405 |  39.364 |  39.884 |  39.519 | 86.377 |
I mace/benchmark/statistics.cc:347] -----------------------------------------------------------------------
I mace/benchmark/statistics.cc:347] 
I mace/benchmark/statistics.cc:347] 77 ops total.
I mace/libmace/mace.cc:603] Destroying MaceEngine
Benchmark done! 
```
