### ISSUE TITLE
Run example on RK3399 with GPU Fall back to CPU

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#529]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ununtu16
- **NDK version(e.g., 15c)**:
17
- **GCC version(if compiling for host, e.g., 5.4.0)**:

- **MACE version (Use the command: git describe --long --tags)**:
master
- **Python version(2.7)**: 
2.7
- **Bazel version (e.g., 0.13.0)**:
13.0
### Model deploy file (*.yml)
```yaml
......
# The name of library
library_name: libunitest
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  teacher: # model tag, which will be used in model loading and must be specific.
    platform: tensorflow
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /home/administrator/Code/share/mace/new_mace/sphereface-sphere_64_bggr_cosface_box_0-975000_features.pb
    # sha256_checksum of your model's pb file.
    # use this command to get the sha256_checksum: sha256sum path/to/your/pb/file
    model_sha256_checksum: f3bdc80bba9160b3344fbaefafff80ff1fc72ca533116b62f780baf258668cb8
    # define your model's interface
    # if there multiple inputs or outputs, write like blow:
    subgraphs:
      - input_tensors:
          - input
    #     - input1
        input_shapes:
          - 1,64,64,4
    #     - 1,224,224,3
        output_tensors:
          - Resface/Bottleneck/BatchNorm/FusedBatchNorm
    #      - output1
        output_shapes:
          - 1,1,1,512
    #      - 1,1001
    # cpu, gpu or cpu+gpu
    runtime: gpu
    obfuscate: 1
    winograd: 4


```

### Describe the problem
I am running mace performance test on RK3399 GPU 
python3 tools/converter.py convert --config=/home/administrator/Code/share/mace/new_mace/FA_models_3.yml

python3 tools/converter.py run --config=/home/administrator/Code/share/mace/new_mace/FA_models_3.yml  --round=10

And it failed to run on GPU!!!???

### Error information / logs
 python3 tools/converter.py run --config=/home/administrator/Code/share/mace/new_mace/FA_models_3.yml  --round=100
* Build //mace/tools/validation:mace_run_static with ABI arm64-v8a
WARNING: ignoring http_proxy in environment.
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 17. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16]. Bazel will attempt to treat the NDK as if it was r16. This may cause compilation and linkage problems. Please download a supported NDK version.
INFO: Analysed target //mace/tools/validation:mace_run_static (1 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 1.407s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
('build', '//mace/tools/validation:mace_run_static', '--config', 'android', '--cpu=arm64-v8a', '--define', 'neon=true', '--define', 'openmp=false', '--define', 'opencl=true', '--define', 'quantize=false', '--define', 'hexagon=false', '--define', 'hta=false', '--define', 'apu=false', '--config', 'optimization', '--config', 'symbol_hidden')
Build done!

*******************************************************
          Run model teacher on Firefly-RK3399          
*******************************************************

Generate input file:  build/libunitest/_tmp/teacher/3e2b51b8ce4724bea30161fb3c936745/Firefly-RK3399_rk3399/arm64-v8a/model_input_input
Generate input file done.
* Run 'teacher' with round=100, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push build/libunitest/_tmp/teacher/3e2b51b8ce4724bea30161fb3c936745/Firefly-RK3399_rk3399/arm64-v8a/model_input_input to /data/local/tmp/mace_run
Push build/libunitest/model/teacher.data to /data/local/tmp/mace_run
Push build/libunitest/model/teacher.pb to /data/local/tmp/mace_run/teacher.pb
Push build/libunitest/_tmp/arm64-v8a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-teacher-1568037556.1706104 to /data/local/tmp/mace_run/cmd_file-teacher-1568037556.1706104
I mace/tools/validation/mace_run.cc:462] model name: teacher
I mace/tools/validation/mace_run.cc:463] mace version: v0.11.0-rc0-110-g03362fa
I mace/tools/validation/mace_run.cc:464] input node: input
I mace/tools/validation/mace_run.cc:465] input shape: 1,64,64,4
I mace/tools/validation/mace_run.cc:466] output node: Resface/Bottleneck/BatchNorm/FusedBatchNorm
I mace/tools/validation/mace_run.cc:467] output shape: 1,1,1,512
I mace/tools/validation/mace_run.cc:468] input_file: /data/local/tmp/mace_run/model_input
I mace/tools/validation/mace_run.cc:469] output_file: /data/local/tmp/mace_run/model_out
I mace/tools/validation/mace_run.cc:470] model_data_file: /data/local/tmp/mace_run/teacher.data
I mace/tools/validation/mace_run.cc:471] model_file: /data/local/tmp/mace_run/teacher.pb
I mace/tools/validation/mace_run.cc:472] device: GPU
I mace/tools/validation/mace_run.cc:473] round: 100
I mace/tools/validation/mace_run.cc:474] restart_round: 1
I mace/tools/validation/mace_run.cc:475] gpu_perf_hint: 3
I mace/tools/validation/mace_run.cc:476] gpu_priority_hint: 3
I mace/tools/validation/mace_run.cc:477] omp_num_threads: -1
I mace/tools/validation/mace_run.cc:478] cpu_affinity_policy: 1
I mace/libmace/mace.cc:430] Creating MaceEngine, MACE version: v0.11.0-rc0-110-g03362fa
I mace/libmace/mace.cc:469] Initializing MaceEngine
I mace/libmace/mace.cc:602] Destroying MaceEngine
I mace/tools/validation/mace_run.cc:519] restart round 0
E ./mace/utils/tuner.h:170] Failed to read tuned param file: /data/local/tmp/mace_run/libunitest_tuned_opencl_parameter.Firefly-RK3399.rk3399.bin
I mace/libmace/mace.cc:875] Create MaceEngine from model graph proto and weights data
I mace/libmace/mace.cc:430] Creating MaceEngine, MACE version: v0.11.0-rc0-110-g03362fa
E mace/core/kv_storage.cc:109] Failed to read kv store file: /data/local/tmp/mace_run/interior//mace_cl_compiled_program.bin
W mace/core/runtime/opencl/opencl_runtime.cc:382] Load OpenCL cached compiled kernel file failed. Please make sure the storage directory exist and you have Write&Read permission
I mace/libmace/mace.cc:469] Initializing MaceEngine
I mace/core/net_def_adapter.cc:348] Op d019f091 fall back to CPU
I mace/core/net_def_adapter.cc:348] Op 59ce7a42 fall back to CPU
I mace/tools/validation/mace_run.cc:268] Create Mace Engine latency: 1891.87 ms
I mace/tools/validation/mace_run.cc:275] Total init latency: 1892.24 ms
acc in=65536
output_size =2048
I mace/tools/validation/mace_run.cc:326] Warm up run
I mace/tools/validation/mace_run.cc:362] 1st warm up run latency: 2851.67 ms
I mace/tools/validation/mace_run.cc:369] Run model
I mace/tools/validation/mace_run.cc:420] Average latency: 785.491 ms
========================================================
     capability(CPU)        init      warmup     run_avg
========================================================
time          47.533    1892.243    2851.674     785.491
I mace/tools/validation/mace_run.cc:442] Write output file /data/local/tmp/mace_run/model_out_Resface_Bottleneck_BatchNorm_FusedBatchNorm with size 2048 done.
I mace/libmace/mace.cc:602] Destroying MaceEngine
Running finished!

Elapse time: 1.647197 minutes.
* Package libs for libunitest
Start packaging 'libunitest' libs into build/libunitest/libmace_libunitest.tar.gz
build/libunitest/model/
build/libunitest/model/teacher.pb
build/libunitest/model/gpu/
build/libunitest/model/teacher.data
Packaging Done!
