### ISSUE TITLE
Quantized operator list

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#551]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **NDK version(e.g., 15c)**: 18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: 0.11.0-rc0
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.16.0

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: sp
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  sp: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /models/sp/test.prototxt
    weight_file_path: /models/sp/test.caffemodel
    # sha256_checksum of your model's pb file.
    # use this command to get the sha256_checksum --> sha256sum path/to/your/pb/file
    model_sha256_checksum: e45ccada591840b0ec270c22e5652c278a11cd96297fa4b1a5c19e6aa62bc124
    weight_sha256_checksum: 2b84e9b511cbf6d2896c4cd7517920be96e394a3ad35bc940a9c56436b92b61a
    # define your model's interface
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,112,112
        input_data_formats:
          - NCHW
        output_tensors:
          - fc1
        output_shapes:
          - 1,512,1,1
        output_data_formats:
          - NCHW
    obfuscate: 0
    quantize: 1
    quantize_range_file: /models/sp/overall_range
    runtime: cpu # cpu, gpu or cpu+gpu or dsp
    winograd: 0
```

### Describe the problem
Some op is not supported for quantization. Is there a list of supported quantized ops?

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
F mace/core/operator.cc:324] Key not registered: Activation0T_DT_UINT8
F mace/core/operator.cc:324] backtrace:
F mace/core/operator.cc:324]  pc 0x60f8fa95f8
F mace/core/operator.cc:324]  pc 0x60f8fac7e8
F mace/core/operator.cc:324]  pc 0x60f8fac724
F mace/core/operator.cc:324]  pc 0x60f8facc64
F mace/core/operator.cc:324]  pc 0x60f8facd74
F mace/core/operator.cc:324]  pc 0x60f8f87704
F mace/core/operator.cc:324]  pc 0x60f8f77628
F mace/core/operator.cc:324]  pc 0x60f8e7b91c
F mace/core/operator.cc:324]  pc 0x60f8e823c0
F mace/core/operator.cc:324]  pc 0x60f8e5ed28
F mace/core/operator.cc:324]  pc 0x60f8e61e10
F mace/core/operator.cc:324]  pc 0x60f8e62974
F mace/core/operator.cc:324]  pc 0x7f2747c590 __libc_init
F mace/core/operator.cc:324]  pc 0x60f8e5e328
Aborted
ERROR: [Mace Run] /mace/tools/device.py:358: Mace run failed.
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
