### ISSUE TITLE
Caught undefined reference error when building Android example app with CMake-built MACE static library

### ISSUE THREAD

**Issue by mexeniz** [XiaoMi/mace#573]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu16.04 (MACE Docker image)
- **NDK version(e.g., 15c)**: 18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- **MACE version (Use the command: git describe --long --tags)**: 0.12.0
- **Python version(2.7)**: 3.6
- **Bazel version (e.g., 0.13.0)**: [0.16.0]

- **CMake version**: 3.16.0

### Model deploy file (*.yml)
```yaml
library_name: mobilenet
target_abis: [arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0
  mobilenet_v2:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet-v2-1.0.pb
    model_sha256_checksum: 369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0
  mobilenet_v1_quant:
    platform: tensorflow
    model_file_path: http://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet_v1_1.0_224_quant_retrain.pb
    model_sha256_checksum: c3faa9bd790310eb3dec411d2f2e2dd8802394e31ccb47daaa5e3b6369fadfa3
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        input_ranges:
          - -1.0,1.0
        output_tensors:
          - MobilenetV1/Predictions/Softmax:0
        output_shapes:
          - 1,1001
    runtime: cpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0
    quantize: 1
  mobilenet_v2_quant:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet_v2_1.0_224_quant_retrain.pb
    model_sha256_checksum: 1429c8e2a91b251c9fa0dae43dfa5817c5a798bd30284f8c0690e7569a8817f1
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        input_ranges:
          - -1.0,1.0
        output_tensors:
          - output
        output_shapes:
          - 1,1001
    runtime: cpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0
    quantize: 1

```

### Describe the problem
After I built the MACE library by running `./tools/cmake/cmake-build-arm64-v8a.sh` and converted example Mobilenet models, I tried to build Android application which is provided in `mace/examples/android`. The errors of undefined reference were thrown right away. 
I have also noticed that there were many lib files in an output folder and the size of a CMake-built static library file (~~ 6 MB) seemed to be incorrect comparing to a Bazel-built static library (~~ 330 MB). All lib files built by CMake are provided in `Error information / logs` section. 

I have 2 questions about this issue:
1. How can I fix these undefined reference errors?
2. According to [Advanced usage for CMake users — MACE documentation](https://mace.readthedocs.io/en/latest/user_guide/advanced_usage_cmake.html), I found that `When you need to integrate the libraries into your applications, you can link libmace_static.a and libmodel.a to your target`, but I am not if not sure it the other lib files should be included in the same folder or not. For Android integration, which library files should I copy to Android project?

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. bash tools/cmake/cmake-build-arm64-v8a.sh
3. python tools/converter.py convert --config_file=/path/to/mace/examples/android/mobilenet.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
- Full CMake error log can be found here [cmake-err.log](https://github.com/XiaoMi/mace/files/3948038/cmake-err.log). The sample logs are below.
```bash
[1/1] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libmace_mobile_jni.so
FAILED: : && /home/munix/Android/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=aarch64-none-linux-android21 --gcc-toolchain=/home/munix/Android/android-ndk-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/home/munix/Android/android-ndk-r18b/sysroot -fPIC -isystem /home/munix/Android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -fopenmp -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /home/munix/Android/android-ndk-r18b/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/home/munix/Android/android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libmace_mobile_jni.so -o ../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libmace_mobile_jni.so CMakeFiles/mace_mobile_jni.dir/src/main/cpp/image_classify.cc.o  ../../../../src/main/cpp/model/arm64-v8a/mobilenet.a ../../../../src/main/cpp/lib/arm64-v8a/libcore.a /home/munix/Android/android-ndk-r18b/platforms/android-21/arch-arm64/usr/lib/liblog.so -latomic -lm "/home/munix/Android/android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a" "/home/munix/Android/android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++abi.a" && :
CMakeFiles/mace_mobile_jni.dir/src/main/cpp/image_classify.cc.o: In function `mace::CreateMaceEngineFromCode(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, mace::MaceEngineConfig const&, std::__ndk1::shared_ptr<mace::MaceEngine>*)':
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:109: undefined reference to `mace::MaceStatus::MaceStatus(mace::MaceStatus::Code)'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:114: undefined reference to `mace::MaceStatus::MaceStatus(mace::MaceStatus::Code)'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:118: undefined reference to `mace::MaceEngine::MaceEngine(mace::MaceEngineConfig const&)'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:120: undefined reference to `mace::MaceEngine::Init(mace::NetDef const*, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, unsigned char const*)'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:120: undefined reference to `mace::MaceStatus::operator=(mace::MaceStatus const&&)'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:120: undefined reference to `mace::MaceStatus::~MaceStatus()'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:120: undefined reference to `mace::MaceStatus::~MaceStatus()'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:125: undefined reference to `mace::MaceEngine::MaceEngine(mace::MaceEngineConfig const&)'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:127: undefined reference to `mace::MaceEngine::Init(mace::NetDef const*, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, unsigned char const*)'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:127: undefined reference to `mace::MaceStatus::operator=(mace::MaceStatus const&&)'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:127: undefined reference to `mace::MaceStatus::~MaceStatus()'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:127: undefined reference to `mace::MaceStatus::~MaceStatus()'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:132: undefined reference to `mace::MaceEngine::MaceEngine(mace::MaceEngineConfig const&)'
/home/munix/workspace/mace-ss/mace/examples/android/macelibrary/.externalNativeBuild/cmake/debug/arm64-v8a/../../../../src/main/cpp/include/mace/public/mace_engine_factory.h:134: undefined reference to `mace::MaceEngine::Init(mace::NetDef const*, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&, unsigned char const*)'
.
.
.
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op0.o): In function `google::protobuf::RepeatedPtrField<mace::Argument>::TypeHandler::Type* google::protobuf::internal::RepeatedPtrFieldBase::Add<google::protobuf::RepeatedPtrField<mace::Argument>::TypeHandler>(google::protobuf::RepeatedPtrField<mace::Argument>::TypeHandler::Type*)':
/proc/self/cwd/external/com_google_protobuf/src/google/protobuf/repeated_field.h:1532: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op0.o): In function `google::protobuf::internal::GenericTypeHandler<mace::Argument>::New(google::protobuf::Arena*)':
/proc/self/cwd/external/com_google_protobuf/src/google/protobuf/repeated_field.h:643: undefined reference to `mace::Argument* google::protobuf::Arena::CreateMaybeMessage<mace::Argument>(google::protobuf::Arena*)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op0.o): In function `google::protobuf::RepeatedPtrField<mace::Argument>::TypeHandler::Type* google::protobuf::internal::RepeatedPtrFieldBase::Add<google::protobuf::RepeatedPtrField<mace::Argument>::TypeHandler>(google::protobuf::RepeatedPtrField<mace::Argument>::TypeHandler::Type*)':
/proc/self/cwd/external/com_google_protobuf/src/google/protobuf/repeated_field.h:1532: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op0.o): In function `google::protobuf::internal::GenericTypeHandler<mace::Argument>::New(google::protobuf::Arena*)':
/proc/self/cwd/external/com_google_protobuf/src/google/protobuf/repeated_field.h:643: undefined reference to `mace::Argument* google::protobuf::Arena::CreateMaybeMessage<mace::Argument>(google::protobuf::Arena*)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op0.o): In function `google::protobuf::RepeatedPtrField<mace::Argument>::TypeHandler::Type* google::protobuf::internal::RepeatedPtrFieldBase::Add<google::protobuf::RepeatedPtrField<mace::Argument>::TypeHandler>(google::protobuf::RepeatedPtrField<mace::Argument>::TypeHandler::Type*)':
/proc/self/cwd/external/com_google_protobuf/src/google/protobuf/repeated_field.h:1532: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
../../../../src/main/cpp/model/arm64-v8a/mobilenet.a(op0.o): In function `google::protobuf::internal::GenericTypeHandler<mace::Argument>::New(google::protobuf::Arena*)':
/proc/self/cwd/external/com_google_protobuf/src/google/protobuf/repeated_field.h:643: undefined reference to `mace::Argument* google::protobuf::Arena::CreateMaybeMessage<mace::Argument>(google::protobuf::Arena*)'
```
- Total library files from CMake build :
```
root@munix-ZenBook:/mace/cmake-build/arm64-v8a/install/lib# ls -alh
total 175M
drwxr-xr-x 2 root root 4.0K Dec  4 14:11 .
drwxr-xr-x 5 root root 4.0K Dec  4 14:11 ..
-rw-r--r-- 1 root root  19M Dec  4 14:11 libcore.a
-rw-r--r-- 1 root root 1.6M Dec  4 14:11 libgenerated_opencl_kernel.a
-rw-r--r-- 1 root root 3.9K Dec  4 14:11 libgenerated_version.a
-rw-r--r-- 1 root root 1.4M Dec  4 14:11 libmace.so
-rw-r--r-- 1 root root 6.3M Dec  4 14:11 libmace_static.a
-rw-r--r-- 1 root root  980 Dec  4 14:11 libmodel.a
-rw-r--r-- 1 root root 5.7K Dec  4 14:11 libmodel_shared.so
-rw-r--r-- 1 root root 129M Dec  4 14:11 libops.a
-rw-r--r-- 1 root root 1.1M Dec  4 14:11 libport_android.a
-rw-r--r-- 1 root root 682K Dec  4 14:11 libport_base.a
-rw-r--r-- 1 root root 596K Dec  4 14:11 libport_linux_base.a
-rw-r--r-- 1 root root 114K Dec  4 14:11 libport_posix.a
-rw-r--r-- 1 root root 2.0M Dec  4 14:11 libproto.a
-rw-r--r-- 1 root root  10M Dec  4 14:11 libprotobuf-lite.a
-rw-r--r-- 1 root root 4.6M Dec  4 14:11 libutils.a

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

- This how native code structure in Android project (`mace/examples/android/macelibrary/src/main/cpp
`) looks like:
```
.
├── image_classify.cc
├── image_classify.h
├── include
│   └── mace
│       ├── port
│       │   ├── env.h
│       │   ├── file_system.h
│       │   ├── logger.h
│       │   ├── port-arch.h
│       │   └── port.h
│       ├── public
│       │   ├── mace_engine_factory.h
│       │   ├── mace.h
│       │   ├── mobilenet_v1.h
│       │   ├── mobilenet_v1_quant.h
│       │   ├── mobilenet_v2.h
│       │   └── mobilenet_v2_quant.h
│       └── utils
│           ├── logging.h
│           ├── macros.h
│           ├── memory.h
│           └── string_util.h
├── lib
│   └── arm64-v8a
│       ├── libcore.a
│       ├── libgenerated_opencl_kernel.a
│       ├── libgenerated_version.a
│       ├── libmace.so
│       ├── libmace_static.a
│       ├── libmodel.a
│       ├── libmodel_shared.so
│       ├── libops.a
│       ├── libport_android.a
│       ├── libport_base.a
│       ├── libport_linux_base.a
│       ├── libport_posix.a
│       ├── libproto.a
│       ├── libprotobuf-lite.a
│       └── libutils.a
└── model
    └── arm64-v8a
        └── mobilenet.a

```
- Android `CMakeLists.txt` (nothing is modified)
```
cmake_minimum_required(VERSION 3.4.1)

#set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/../app/libs/${ANDROID_ABI})

include_directories(${CMAKE_SOURCE_DIR}/)
include_directories(${CMAKE_SOURCE_DIR}/src/main/cpp)
include_directories(${CMAKE_SOURCE_DIR}/src/main/cpp/include)
file(GLOB LIBMACE "${CMAKE_SOURCE_DIR}/src/main/cpp/lib/arm64-v8a/*")
set(mace_lib ${LIBMACE})
set(mobilenet_lib ${CMAKE_SOURCE_DIR}/src/main/cpp/model/arm64-v8a/mobilenet.a)
add_library (mace_lib SHARED IMPORTED)
set_target_properties(mace_lib PROPERTIES IMPORTED_LOCATION ${mace_lib})
add_library (mobilenet_lib STATIC IMPORTED)
set_target_properties(mobilenet_lib PROPERTIES IMPORTED_LOCATION ${mobilenet_lib})

add_library( # Sets the name of the library.
             mace_mobile_jni
             # Sets the library as a shared library.
             SHARED
             # Provides a relative path to your source file(s).
             src/main/cpp/image_classify.cc )

find_library( # Sets the name of the path variable.
              log-lib
              log )

target_link_libraries( # Specifies the target library.
                       mace_mobile_jni
                       mobilenet_lib
                       mace_lib
                       # Links the target library to the log library
                       # included in the NDK.
                       ${log-lib} )

```
