### ISSUE TITLE
Caught `Check failed` when running a Caffe model with converter.py

### ISSUE THREAD

**Issue by mexeniz** [XiaoMi/mace#593]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu16.04 (MACE Docker image)
- **NDK version(e.g., 15c)**: 18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- **MACE version (Use the command: git describe --long --tags)**: 0.12.0
- **Python version(2.7)**: 3.6
- **Bazel version (e.g., 0.13.0)**: [0.16.0]
- **CMake version**: 3.16.0

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: retina
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  retinanet: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /models/retinanet/caffe_25_160.prototxt
    weight_file_path: /models/retinanet/caffe_25_160.caffemodel
    model_sha256_checksum: 213d764bd605d02b1630740969ab7110a2ee0111e3f8200ce02304cf72fbd42a
    weight_sha256_checksum: c83d575645daf8541867a63197de6bfd44a7fb3bf9bf4c876cde8165c23fac0c
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,160,160
        input_data_formats:
          - NCHW
        output_tensors:
          - face_rpn_cls_prob_reshape_stride32
          - face_rpn_bbox_pred_stride32
          - face_rpn_landmark_pred_stride32
          - face_rpn_cls_prob_reshape_stride16
          - face_rpn_bbox_pred_stride16
          - face_rpn_landmark_pred_stride16
          - face_rpn_cls_prob_reshape_stride8
          - face_rpn_bbox_pred_stride8
          - face_rpn_landmark_pred_stride8
        output_shapes:
          - 1,4,5,5
          - 1,8,5,5
          - 1,20,5,5
          - 1,4,10,10
          - 1,8,10,10
          - 1,20,10,10
          - 1,4,20,20
          - 1,8,20,20
          - 1,20,20,20
        output_data_formats:
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
    obfuscate: 0
    runtime: cpu+gpu 
    winograd: 0
```

### Describe the problem
When I tried to run a model on Xiaomi MI9 with `converter.py`, it failed because of this error: 
```
Check failed: missing * product == input->size() Input size not match reshaped tensor size
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/models/retinanet/retinanet160.yml
3. python tools/converter.py run --config=/models/retinanet/retinanet160.yml --debug_mode
4. adb logcat | $ANDROID_NDK_HOME/ndk-stack -sym builds/model/_tmp/arm64-v8a/
```

### Error information / logs
Please refer to this gist link:
[MACE Error Log · GitHub](https://gist.github.com/mexeniz/1e7845fff1ad54c7bd975f7290c85266)
It provides error logs from `python tools/converter.py run` and `adb logcat`

### Additional context
Followed a workaround from the last answer of this issue https://github.com/XiaoMi/mace/issues/560
```
diff --git a/tools/python/transform/transformer.py b/tools/python/transform/transformer.py
index bb9154f..bbf14b4 100644
--- a/tools/python/transform/transformer.py
+++ b/tools/python/transform/transformer.py
@@ -1353,7 +1353,7 @@ class Transformer(base_converter.ConverterInterface):
         visited = set()
         sorted_nodes = []
 
-        output_nodes = self._option.check_nodes.keys()
+        output_nodes = list(self._option.check_nodes.keys())
         if not self._quantize_activation_info:
             output_nodes.extend(self._option.output_nodes)
         for output_node in output_nodes:
```
