### ISSUE TITLE
Caffe model validation fails on MACE v0.12.0 due to low similarity

### ISSUE THREAD

**Issue by mexeniz** [XiaoMi/mace#595]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu16.04 (MACE Docker image)
- **NDK version(e.g., 15c)**: 18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- **MACE version (Use the command: git describe --long --tags)**: 0.12.0
- **Python version(2.7)**: 3.6
- **Bazel version (e.g., 0.13.0)**: [0.16.0]
- **CMake version**: 3.16.0

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: libretinanet
target_abis: [arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  retinanet:
    platform: caffe
    model_file_path: /models/retinanet/retinanet3.prototxt
    weight_file_path: /models/retinanet/retinanet3.caffemodel
    model_sha256_checksum: 638e05fc466737c3b8fc36261adaaff40cbd4de5a8c72a46b37f2b00f01180e1
    weight_sha256_checksum: 6222910a773c693c23b4765baba4ed8427e9f3c11781060918e6282a297a7437
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,320,320
        input_data_formats:
          - NCHW
        output_tensors:
          - face_rpn_cls_prob_reshape_stride32
          - face_rpn_bbox_pred_stride32
          - face_rpn_landmark_pred_stride32
          - face_rpn_cls_prob_reshape_stride16
          - face_rpn_bbox_pred_stride16
          - face_rpn_landmark_pred_stride16
          - face_rpn_cls_prob_reshape_stride8
          - face_rpn_bbox_pred_stride8
          - face_rpn_landmark_pred_stride8
        output_shapes:
          - 1,4,10,10
          - 1,8,10,10
          - 1,20,10,10
          - 1,4,20,20
          - 1,8,20,20
          - 1,20,20,20
          - 1,4,40,40
          - 1,8,40,40
          - 1,20,40,40
        output_data_formats:
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
    obfuscate: 0
    runtime: gpu
    winograd: 4
```

### Describe the problem
With `MACE v0.12.0`, the output of converted model is significantly different. As a result, it fails to run in validation mode. In addition, I tried to run unit tests on Andorid Studio and found the output difference. 
However, with `MACE v0.11.0-rc1`, the output is fine and the validation runs successfully.
```
========================================================
     capability(CPU)        init      warmup     run_avg
========================================================
time           7.484     877.331    1323.142      16.371
I mace/libmace/mace.cc:636] Destroying MaceEngine
Running finished!

* Validate with caffe
Pull /data/local/tmp/mace_run/model_out_face_rpn_cls_prob_reshape_stride32 to build/libretinanet/_tmp/retinanet/14a062bf9f488e2a38c1fb60b18a80de/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_bbox_pred_stride32 to build/libretinanet/_tmp/retinanet/14a062bf9f488e2a38c1fb60b18a80de/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_landmark_pred_stride32 to build/libretinanet/_tmp/retinanet/14a062bf9f488e2a38c1fb60b18a80de/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_cls_prob_reshape_stride16 to build/libretinanet/_tmp/retinanet/14a062bf9f488e2a38c1fb60b18a80de/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_bbox_pred_stride16 to build/libretinanet/_tmp/retinanet/14a062bf9f488e2a38c1fb60b18a80de/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_landmark_pred_stride16 to build/libretinanet/_tmp/retinanet/14a062bf9f488e2a38c1fb60b18a80de/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_cls_prob_reshape_stride8 to build/libretinanet/_tmp/retinanet/14a062bf9f488e2a38c1fb60b18a80de/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_bbox_pred_stride8 to build/libretinanet/_tmp/retinanet/14a062bf9f488e2a38c1fb60b18a80de/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_landmark_pred_stride8 to build/libretinanet/_tmp/retinanet/14a062bf9f488e2a38c1fb60b18a80de/MI9_msmnile/arm64-v8a
Traceback (most recent call last):
  File "/mace/validate.py", line 459, in <module>
face_rpn_cls_prob_reshape_stride32 MACE VS CAFFE similarity: 0.7051022200187764 , sqnr: 1.988659806883121 , pixel_accuracy: 0.4
    FLAGS.log_file)
  File "/mace/validate.py", line 371, in validate
    validation_threshold, log_file)
  File "/mace/validate.py", line 262, in validate_caffe_model
    value, validation_threshold, log_file)
  File "/mace/validate.py", line 113, in compare_output
    "", common.StringFormatter.block("Similarity Test Failed"))
TypeError: summary() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "tools/converter.py", line 1151, in <module>
    flags.func(flags)
  File "tools/converter.py", line 938, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/mace/tools/device.py", line 782, in run_specify_abi
    log_file=log_file,
  File "/mace/tools/sh_commands.py", line 756, in validate_model
    _fg=True)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/docker exec mace_caffe_lastest_validator python -u /mace/validate.py --platform=caffe --model_file=/mace/retinanet3.prototxt --weight_file=/mace/retinanet3.caffemodel --input_file=/mace/model_input --mace_out_file=/mace/model_out --device_type=GPU --input_node=data --output_node=face_rpn_cls_prob_reshape_stride32,face_rpn_bbox_pred_stride32,face_rpn_landmark_pred_stride32,face_rpn_cls_prob_reshape_stride16,face_rpn_bbox_pred_stride16,face_rpn_landmark_pred_stride16,face_rpn_cls_prob_reshape_stride8,face_rpn_bbox_pred_stride8,face_rpn_landmark_pred_stride8 --input_shape=1,3,320,320 --output_shape=1,4,10,10:1,8,10,10:1,20,10,10:1,4,20,20:1,8,20,20:1,20,20,20:1,4,40,40:1,8,40,40:1,20,40,40 --input_data_format=NCHW --output_data_format=NCHW,NCHW,NCHW,NCHW,NCHW,NCHW,NCHW,NCHW,NCHW --validation_threshold=0.995000 --input_data_type=float32 --backend=tensorflow --validation_outputs_data= --log_file=

  STDOUT:


  STDERR:

```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/models/retinanet/retinanet3.yml
2. python tools/converter.py run --validate --config_file=/models/retinanet/retinanet3.yml
```

### Error information / logs
Please refer to this gist link for full conversion and validation log:
[MACE v0.12.0 Error log - validation failed · GitHub](https://gist.github.com/mexeniz/dbbc3d6497ae5529490e755ea508e526)

### Additional context
For `MACE v0.12.0`, I followed a workaround from the last answer of this issue https://github.com/XiaoMi/mace/issues/560
```
diff --git a/tools/python/transform/transformer.py b/tools/python/transform/transformer.py
index bb9154f..bbf14b4 100644
--- a/tools/python/transform/transformer.py
+++ b/tools/python/transform/transformer.py
@@ -1353,7 +1353,7 @@ class Transformer(base_converter.ConverterInterface):
         visited = set()
         sorted_nodes = []
 
-        output_nodes = self._option.check_nodes.keys()
+        output_nodes = list(self._option.check_nodes.keys())
         if not self._quantize_activation_info:
             output_nodes.extend(self._option.output_nodes)
         for output_node in output_nodes:
```

**Comment by lu229** [comment]
@mexeniz Is it convenient for you to share the model and yml file? It seems there is a bug in 0.12.0.

**Comment by mexeniz** [comment]
@lu229 Please find the model and yml file in this [link](https://drive.google.com/open?id=1CbG7NhIMiUn3_40U0FkIgRw04MUq65q_).

**Comment by lu229** [comment]
@mexeniz this link is for a pb file,  Is it convenient for  you to share the yml file?

**Comment by mexeniz** [comment]
@lu229 Doesn't `mnet-100.yml` inside the link work?

**Comment by gasgallo** [comment]
@lu229 I'm having the same issue but with a different model ([download](https://drive.google.com/drive/folders/1ntMbOFWhgD-laA_3Y0f1-LBUXi6TUL1P?usp=sharing)). 

When runnng on CPU I get the same error as https://github.com/XiaoMi/mace/issues/602, when running on GPU instead validation fails because of low similarity.
```bash
root@ds017:/mace# python tools/converter.py run --validate --config /models/model/model.yml 
CMD> bazel build //mace/proto:mace_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //mace/proto:mace_py (5 packages loaded)
INFO: Analysed target //mace/proto:mace_py (17 packages loaded).
INFO: Found 1 target...
[0 / 0] no action
Target //mace/proto:mace_py up-to-date:
bazel-genfiles/mace/proto/mace_pb2.py
INFO: Elapsed time: 2.666s, Critical Path: 0.08s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/mace_pb2.py tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //third_party/caffe:caffe_py (5 packages loaded)
INFO: Analysed target //third_party/caffe:caffe_py (17 packages loaded).
INFO: Found 1 target...
[3 / 9] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 2.638s, Critical Path: 0.05s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py tools/python/py_proto

* Build //mace/tools:mace_run_static with ABI arm64-v8a
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 19. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16]. Bazel will attempt to treat the NDK as if it was r16. This may cause compilation and linkage problems. Please download a supported NDK version.
INFO: Analysed target //mace/tools:mace_run_static (32 packages loaded).
INFO: Found 1 target...
Target //mace/tools:mace_run_static up-to-date:
  bazel-bin/mace/tools/mace_run_static
INFO: Elapsed time: 13.294s, Critical Path: 0.67s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
('build', '//mace/tools:mace_run_static', '--config', 'android', '--cpu=arm64-v8a', '--define', 'neon=true', '--define', 'openmp=false', '--define', 'opencl=true', '--define', 'quantize=false', '--define', 'hexagon=false', '--define', 'hta=false', '--define', 'apu=false', '--config', 'optimization', '--config', 'symbol_hidden')
Build done!

*********************************************
          Run model model on MI9          
*********************************************

Generate input file:  build/model/_tmp/model/ddc28d735c49610d3fc72054fc628b9d/MI9_msmnile/arm64-v8a/model_input_data
Generate input file done.
* Run 'model' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push build/model/_tmp/model/ddc28d735c49610d3fc72054fc628b9d/MI9_msmnile/arm64-v8a/model_input_data to /data/local/tmp/mace_run
Push build/model/model/model.data to /data/local/tmp/mace_run
Push build/model/model/model.pb to /data/local/tmp/mace_run/model.pb
Push build/model/_tmp/arm64-v8a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-model-1582613030.6476307 to /data/local/tmp/mace_run/cmd_file-model-1582613030.6476307
I mace/tools/mace_run.cc:527] model name: model
I mace/tools/mace_run.cc:528] mace version: v0.12.0-0-ga610d50
I mace/tools/mace_run.cc:529] input node: data
I mace/tools/mace_run.cc:530] input shape: 1,3,112,112
I mace/tools/mace_run.cc:531] output node: fc1
I mace/tools/mace_run.cc:532] output shape: 1,1,1,512
I mace/tools/mace_run.cc:533] input_file: /data/local/tmp/mace_run/model_input
I mace/tools/mace_run.cc:534] output_file: /data/local/tmp/mace_run/model_out
I mace/tools/mace_run.cc:535] input dir:
I mace/tools/mace_run.cc:536] output dir:
I mace/tools/mace_run.cc:537] model_data_file: /data/local/tmp/mace_run/model.data
I mace/tools/mace_run.cc:538] model_file: /data/local/tmp/mace_run/model.pb
I mace/tools/mace_run.cc:539] device: GPU
I mace/tools/mace_run.cc:540] round: 1
I mace/tools/mace_run.cc:541] restart_round: 1
I mace/tools/mace_run.cc:542] gpu_perf_hint: 3
I mace/tools/mace_run.cc:543] gpu_priority_hint: 3
I mace/tools/mace_run.cc:544] omp_num_threads: -1
I mace/tools/mace_run.cc:545] cpu_affinity_policy: 1
I mace/tools/mace_run.cc:548] limit_opencl_kernel_time: 0
I mace/tools/mace_run.cc:553] opencl_queue_window_size: 0
I mace/libmace/mace.cc:464] Creating MaceEngine, MACE version: v0.12.0-0-ga610d50
I mace/libmace/mace.cc:503] Initializing MaceEngine
I mace/libmace/mace.cc:636] Destroying MaceEngine
I mace/tools/mace_run.cc:596] restart round 0
W ./mace/utils/tuner.h:201] Failed to read tuned param file: /data/local/tmp/mace_run/model_tuned_opencl_parameter.MI9.msmnile.bin
I mace/libmace/mace.cc:911] Create MaceEngine from model graph proto and weights data
I mace/libmace/mace.cc:464] Creating MaceEngine, MACE version: v0.12.0-0-ga610d50
W mace/core/kv_storage.cc:109] Failed to read kv store file: /data/local/tmp/mace_run/interior//mace_cl_compiled_program.bin
W mace/core/runtime/opencl/opencl_runtime.cc:382] Load OpenCL cached compiled kernel file failed. Please make sure the storage directory exist and you have Write&Read permission
I mace/libmace/mace.cc:503] Initializing MaceEngine
I mace/tools/mace_run.cc:269] Create Mace Engine latency: 1946.69 ms
I mace/tools/mace_run.cc:276] Total init latency: 1946.87 ms
I mace/tools/mace_run.cc:370] Warm up run
I mace/tools/mace_run.cc:406] 1st warm up run latency: 1900.17 ms
I mace/tools/mace_run.cc:414] Run model
I mace/tools/mace_run.cc:476] Average latency: 46.425 ms
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_fc1 with size 2048 done.
========================================================
     capability(CPU)        init      warmup     run_avg
========================================================
time          19.510    1946.872    1900.168      46.425
I mace/libmace/mace.cc:636] Destroying MaceEngine
Running finished!

* Validate with caffe
Pull /data/local/tmp/mace_run/model_out_fc1 to build/model/_tmp/model/ddc28d735c49610d3fc72054fc628b9d/MI9_msmnile/arm64-v8a
fc1 MACE VS CAFFE similarity: 0.14432888528173168 , sqnr: 1.732945187139532e-10 , pixel_accuracy: 0.0
ERROR: [] /mace/validate.py:117: ******************************************
          Similarity Test Failed          
******************************************

Traceback (most recent call last):
  File "tools/converter.py", line 1151, in <module>
    flags.func(flags)
  File "tools/converter.py", line 938, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/mace/tools/device.py", line 782, in run_specify_abi
    log_file=log_file,
  File "/mace/tools/sh_commands.py", line 756, in validate_model
    _fg=True)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/docker exec mace_caffe_lastest_validator python -u /mace/validate.py --platform=caffe --model_file=/mace/arc50-caffe.prototxt --weight_file=/mace/arc50-caffe.caffemodel --input_file=/mace/model_input --mace_out_file=/mace/model_out --device_type=GPU --input_node=data --output_node=fc1 --input_shape=1,3,112,112 --output_shape=1,1,1,512 --input_data_format=NCHW --output_data_format=NHWC --validation_threshold=0.995000 --input_data_type=float32 --backend=tensorflow --validation_outputs_data= --log_file=

  STDOUT:


  STDERR:
```

**Comment by lu229** [comment]
@mexeniz Sorry for late reply, please use the v0.12.0 and apply this [patch](https://github.com/lu229/repository/blob/master/issue599.patch). with v0.12.0 I have checked your model and found no errors.

**Comment by mexeniz** [comment]
@lu229 The patch works fine with weight-reset model which I shared with you. Could you also test with this model >> [link](https://drive.google.com/drive/folders/1MeBS7oKOdey2vSfQ-_IJhItqfYH6MJX_?usp=sharing)? I found the patch doesn't work with it.

## Error log
```
********************************************
          Run model mnet_25 on MI9          
********************************************

Generate input file:  build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a/model_input_data
Generate input file done.
* Run 'mnet_25' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a/model_input_data to /data/local/tmp/mace_run
Push build/mnet_25/model/mnet_25.data to /data/local/tmp/mace_run
Push build/mnet_25/model/mnet_25.pb to /data/local/tmp/mace_run/mnet_25.pb
Push build/mnet_25/_tmp/arm64-v8a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-mnet_25-1583209779.106115 to /data/local/tmp/mace_run/cmd_file-mnet_25-1583209779.106115
I mace/tools/mace_run.cc:527] model name: mnet_25
I mace/tools/mace_run.cc:528] mace version: v0.12.0-0-ga610d50
I mace/tools/mace_run.cc:529] input node: data
I mace/tools/mace_run.cc:530] input shape: 1,3,160,160
I mace/tools/mace_run.cc:531] output node: face_rpn_cls_prob_reshape_stride32,face_rpn_bbox_pred_stride32,face_rpn_landmark_pred_stride32,face_rpn_cls_prob_reshape_stride16,face_rpn_bbox_pred_stride16,face_rpn_landmark_pred_stride16,face_rpn_cls_prob_reshape_stride8,face_rpn_bbox_pred_stride8,face_rpn_landmark_pred_stride8
I mace/tools/mace_run.cc:532] output shape: 1,4,5,5:1,8,5,5:1,20,5,5:1,4,10,10:1,8,10,10:1,20,10,10:1,4,20,20:1,8,20,20:1,20,20,20
I mace/tools/mace_run.cc:533] input_file: /data/local/tmp/mace_run/model_input
I mace/tools/mace_run.cc:534] output_file: /data/local/tmp/mace_run/model_out
I mace/tools/mace_run.cc:535] input dir:
I mace/tools/mace_run.cc:536] output dir:
I mace/tools/mace_run.cc:537] model_data_file: /data/local/tmp/mace_run/mnet_25.data
I mace/tools/mace_run.cc:538] model_file: /data/local/tmp/mace_run/mnet_25.pb
I mace/tools/mace_run.cc:539] device: GPU
I mace/tools/mace_run.cc:540] round: 1
I mace/tools/mace_run.cc:541] restart_round: 1
I mace/tools/mace_run.cc:542] gpu_perf_hint: 3
I mace/tools/mace_run.cc:543] gpu_priority_hint: 3
I mace/tools/mace_run.cc:544] omp_num_threads: -1
I mace/tools/mace_run.cc:545] cpu_affinity_policy: 1
I mace/tools/mace_run.cc:548] limit_opencl_kernel_time: 0
I mace/tools/mace_run.cc:553] opencl_queue_window_size: 0
I mace/libmace/mace.cc:464] Creating MaceEngine, MACE version: v0.12.0-0-ga610d50
I mace/libmace/mace.cc:503] Initializing MaceEngine
I mace/libmace/mace.cc:636] Destroying MaceEngine
I mace/tools/mace_run.cc:596] restart round 0
W ./mace/utils/tuner.h:201] Failed to read tuned param file: /data/local/tmp/mace_run/mnet_25_tuned_opencl_parameter.MI9.msmnile.bin
I mace/libmace/mace.cc:911] Create MaceEngine from model graph proto and weights data
I mace/libmace/mace.cc:464] Creating MaceEngine, MACE version: v0.12.0-0-ga610d50
W mace/core/kv_storage.cc:109] Failed to read kv store file: /data/local/tmp/mace_run/interior//mace_cl_compiled_program.bin
W mace/core/runtime/opencl/opencl_runtime.cc:382] Load OpenCL cached compiled kernel file failed. Please make sure the storage directory exist and you have Write&Read permission
I mace/libmace/mace.cc:503] Initializing MaceEngine
I mace/tools/mace_run.cc:269] Create Mace Engine latency: 1198.1 ms
I mace/tools/mace_run.cc:276] Total init latency: 1198.27 ms
I mace/tools/mace_run.cc:370] Warm up run
I mace/tools/mace_run.cc:406] 1st warm up run latency: 1129.85 ms
I mace/tools/mace_run.cc:414] Run model
I mace/tools/mace_run.cc:476] Average latency: 4.427 ms
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_face_rpn_cls_prob_reshape_stride32 with size 400 done.
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_face_rpn_bbox_pred_stride32 with size 800 done.
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_face_rpn_landmark_pred_stride32 with size 2000 done.
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_face_rpn_cls_prob_reshape_stride16 with size 1600 done.
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_face_rpn_bbox_pred_stride16 with size 3200 done.
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_face_rpn_landmark_pred_stride16 with size 8000 done.
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_face_rpn_cls_prob_reshape_stride8 with size 6400 done.
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_face_rpn_bbox_pred_stride8 with size 12800 done.
I mace/tools/mace_run.cc:491] Write output file /data/local/tmp/mace_run/model_out_face_rpn_landmark_pred_stride8 with size 32000 done.
========================================================
     capability(CPU)        init      warmup     run_avg
========================================================
time          20.000    1198.269    1129.846       4.427
I mace/libmace/mace.cc:636] Destroying MaceEngine
Running finished!

* Validate with caffe
Pull /data/local/tmp/mace_run/model_out_face_rpn_cls_prob_reshape_stride32 to build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_bbox_pred_stride32 to build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_landmark_pred_stride32 to build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_cls_prob_reshape_stride16 to build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_bbox_pred_stride16 to build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_landmark_pred_stride16 to build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_cls_prob_reshape_stride8 to build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_bbox_pred_stride8 to build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a
Pull /data/local/tmp/mace_run/model_out_face_rpn_landmark_pred_stride8 to build/mnet_25/_tmp/mnet_25/a1aaa7a100e9fbac708fc05b70908f03/MI9_msmnile/arm64-v8a
face_rpn_cls_prob_reshape_stride32 MACE VS CAFFE similarity: 0.7003569385254784 , sqnr: 1.9619648202616364 , pixel_accuracy: 0.5
ERROR: [] /mace/validate.py:117: ******************************************
          Similarity Test Failed          
******************************************

Traceback (most recent call last):
  File "tools/converter.py", line 1151, in <module>
    flags.func(flags)
  File "tools/converter.py", line 938, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/mace/tools/device.py", line 782, in run_specify_abi
    log_file=log_file,
  File "/mace/tools/sh_commands.py", line 756, in validate_model
    _fg=True)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/docker exec mace_caffe_lastest_validator python -u /mace/validate.py --platform=caffe --model_file=/mace/mnet.25.prototxt --weight_file=/mace/mnet.25.caffemodel --input_file=/mace/model_input --mace_out_file=/mace/model_out --device_type=GPU --input_node=data --output_node=face_rpn_cls_prob_reshape_stride32,face_rpn_bbox_pred_stride32,face_rpn_landmark_pred_stride32,face_rpn_cls_prob_reshape_stride16,face_rpn_bbox_pred_stride16,face_rpn_landmark_pred_stride16,face_rpn_cls_prob_reshape_stride8,face_rpn_bbox_pred_stride8,face_rpn_landmark_pred_stride8 --input_shape=1,3,160,160 --output_shape=1,4,5,5:1,8,5,5:1,20,5,5:1,4,10,10:1,8,10,10:1,20,10,10:1,4,20,20:1,8,20,20:1,20,20,20 --input_data_format=NCHW --output_data_format=NCHW,NCHW,NCHW,NCHW,NCHW,NCHW,NCHW,NCHW,NCHW --validation_threshold=0.995000 --input_data_type=float32 --backend=tensorflow --validation_outputs_data= --log_file=

  STDOUT:


  STDERR:


```

**Comment by gasgallo** [comment]
That model fails validation for me too.

@lu229 Is `Reshape` op supported on GPU with NCHW format? I think that might be the issue.

**Comment by lu229** [comment]
@mexeniz It seems that MACE has a bug in the support of the Split layer from Caffe, I'm busy these days, you can debug it yourself (reference [this](https://mace.readthedocs.io/en/latest/development/how_to_debug.html#debug-correctness))or I'll check it out in few days.

**Comment by lu229** [comment]
@gasgallo yes reshape op is supported on GPU with NCHW,  the issue in the the new model is not caused by Reshape op.

**Comment by gasgallo** [comment]
> @gasgallo yes reshape op is supported on GPU with NCHW, the issue in the the new model is not caused by Reshape op.

Ok, I'll further debug. My guess was `Reshape` because if I set the output node to the one right before the `Reshape` op, then validation is successful.

**Comment by lu229** [comment]
@gasgallo Is your model fully same as the @mexeniz 's model ?  if not, could you submit an new issue for your model,? which helps us analyze and track the problem.

**Comment by gasgallo** [comment]
@lu229 I'm testing exactly the same model.

You can use the following `yaml` file instead of the one shared by @mexeniz, that prunes the outputs to just before the `Reshape` ops.
```yaml
# The name of library
library_name: mnet_25
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mnet_25: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /models/retinaFace/mnet.25/mnet.25.prototxt
    weight_file_path: /models/retinaFace/mnet.25/mnet.25.caffemodel
    model_sha256_checksum: 213d764bd605d02b1630740969ab7110a2ee0111e3f8200ce02304cf72fbd42a
    weight_sha256_checksum: c83d575645daf8541867a63197de6bfd44a7fb3bf9bf4c876cde8165c23fac0c
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,160,160
        input_data_formats:
          - NCHW
        output_tensors:
          - face_rpn_cls_score_stride32
          - face_rpn_bbox_pred_stride32
          - face_rpn_landmark_pred_stride32
          - face_rpn_cls_score_stride16
          - face_rpn_bbox_pred_stride16
          - face_rpn_landmark_pred_stride16
          - face_rpn_cls_score_stride8
          - face_rpn_bbox_pred_stride8
          - face_rpn_landmark_pred_stride8
        output_shapes:
          - 1,4,5,5
          - 1,8,5,5
          - 1,20,5,5
          - 1,4,10,10
          - 1,8,10,10
          - 1,20,10,10
          - 1,4,20,20
          - 1,8,20,20
          - 1,20,20,20
        output_data_formats:
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
          - NCHW
    obfuscate: 0
    runtime: gpu # cpu, gpu or cpu+gpu or dsp
    winograd: 0
```
With this configuration file, the validation is successful!

Also the model validation is successful when using MACE `v0.11.0-rc0` but in this case `Reshape` op isn't implemented on GPU, indeed it falls back to CPU. This might be one more clue that the new `Reshape` GPU op introduced in MACE `v0.12.0` might have some bugs.
