### ISSUE TITLE
Test similarity fails: NaN

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#599]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **NDK version(e.g., 15c)**: 18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: 0.11.0-rc0
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.16.0

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: FD
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  RF: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /models/model.prototxt
    weight_file_path: /models/model.caffemodel
    # sha256_checksum of your model's pb file.
    # use this command to get the sha256_checksum --> sha256sum path/to/your/pb/file
    model_sha256_checksum: e1fc999628c539a9631806a033b302262fac43ae6855b005d37bfbe4b11b5b43
    weight_sha256_checksum: 88815164b0d8f94617f33cdecc036e034c6f1a5a4e4f89b8599cdaec5c86bc34
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,112,112
        input_data_formats:
          - NCHW
        output_tensors:
          - fc1
        output_shapes:
          - 1,1,1,512
    obfuscate: 0
    runtime: cpu+gpu
    winograd: 4
```

### Describe the problem
Validation tests fails because of `nan` similarity.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
2. python tools/converter.py run --config_file=/path/to/your/model_deployment_file --validate
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
root@ds017:/mace# python tools/converter.py run --validate --config /models/model.yml 
* Build //mace/tools/validation:mace_run_static with ABI arm64-v8a
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/tools/validation:mace_run_static (32 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 8.693s, Critical Path: 0.38s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

*********************************************
          Run model model on MI9          
*********************************************

Generate input file:  builds/model/_tmp/model/744eef2ab458803da13359fa3ae0f6af/MI9_msmnile/arm64-v8a/model_input_data
Generate input file done.
* Run 'model' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/model/_tmp/model/744eef2ab458803da13359fa3ae0f6af/MI9_msmnile/arm64-v8a/model_input_data to /data/local/tmp/mace_run
Push builds/model/model/model.data to /data/local/tmp/mace_run
Push builds/model/model/model.pb to /data/local/tmp/mace_run/model.pb
Push builds/model/_tmp/arm64-v8a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-model-1582184289.84 to /data/local/tmp/mace_run/cmd_file-model-1582184289.84
I mace/tools/validation/mace_run.cc:451] model name: model
I mace/tools/validation/mace_run.cc:452] mace version: v0.11.0-rc0-0-g2d650b6
I mace/tools/validation/mace_run.cc:453] input node: data
I mace/tools/validation/mace_run.cc:454] input shape: 1,3,112,112
I mace/tools/validation/mace_run.cc:455] output node: fc1
I mace/tools/validation/mace_run.cc:456] output shape: 1,1,1,512
I mace/tools/validation/mace_run.cc:457] input_file: /data/local/tmp/mace_run/model_input
I mace/tools/validation/mace_run.cc:458] output_file: /data/local/tmp/mace_run/model_out
I mace/tools/validation/mace_run.cc:459] model_data_file: /data/local/tmp/mace_run/model.data
I mace/tools/validation/mace_run.cc:460] model_file: /data/local/tmp/mace_run/model.pb
I mace/tools/validation/mace_run.cc:461] device: CPU
I mace/tools/validation/mace_run.cc:462] round: 1
I mace/tools/validation/mace_run.cc:463] restart_round: 1
I mace/tools/validation/mace_run.cc:464] gpu_perf_hint: 3
I mace/tools/validation/mace_run.cc:465] gpu_priority_hint: 3
I mace/tools/validation/mace_run.cc:466] omp_num_threads: -1
I mace/tools/validation/mace_run.cc:467] cpu_affinity_policy: 1
I mace/libmace/mace.cc:431] Creating MaceEngine, MACE version: v0.11.0-rc0-0-g2d650b6
I mace/libmace/mace.cc:470] Initializing MaceEngine
I mace/libmace/mace.cc:603] Destroying MaceEngine
I mace/tools/validation/mace_run.cc:508] restart round 0
I mace/libmace/mace.cc:876] Create MaceEngine from model graph proto and weights data
I mace/libmace/mace.cc:431] Creating MaceEngine, MACE version: v0.11.0-rc0-0-g2d650b6
I mace/libmace/mace.cc:470] Initializing MaceEngine
I mace/tools/validation/mace_run.cc:265] Create Mace Engine latency: 179.324 ms
I mace/tools/validation/mace_run.cc:272] Total init latency: 179.422 ms
I mace/tools/validation/mace_run.cc:313] Warm up run
I mace/tools/validation/mace_run.cc:349] 1st warm up run latency: 333.755 ms
I mace/tools/validation/mace_run.cc:356] Run model
I mace/tools/validation/mace_run.cc:407] Average latency: 138.55 ms
========================================================
     capability(CPU)        init      warmup     run_avg
========================================================
time          18.938     179.422     333.755     138.550
I mace/tools/validation/mace_run.cc:430] Write output file /data/local/tmp/mace_run/model_out_fc1 with size 2048 done.
I mace/libmace/mace.cc:603] Destroying MaceEngine
Running finished!

* Validate with caffe
Pull /data/local/tmp/mace_run/model_out_fc1 to builds/model/_tmp/model/744eef2ab458803da13359fa3ae0f6af/MI9_msmnile/arm64-v8a
/mace/validate.py:67: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
fc1 MACE VS CAFFE similarity: nan , sqnr: 0.0 , pixel_accuracy: 1.0
ERROR: [] /mace/validate.py:113: ******************************************
          Similarity Test Failed          
******************************************

Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1031, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/mace/tools/device.py", line 779, in run_specify_abi
    log_file=log_file,
  File "/mace/tools/sh_commands.py", line 827, in validate_model
    _fg=True)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/docker exec mace_caffe_lastest_validator python -u /mace/validate.py --platform=caffe --model_file=/mace/test.prototxt --weight_file=/mace/test.caffemodel --input_file=/mace/model_input --mace_out_file=/mace/model_out --device_type=CPU --input_node=data --output_node=fc1 --input_shape=1,3,112,112 --output_shape=1,1,1,512 --input_data_format=NCHW --output_data_format=NHWC --validation_threshold=0.999000 --input_data_type=float32 --backend=tensorflow --validation_outputs_data= --log_file=

  STDOUT:


  STDERR:
```
