### ISSUE TITLE
The issue when run python tools/python/convert.py --config path/to/model.yaml

### ISSUE THREAD

**Issue by ramawidrap** [XiaoMi/mace#605]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution : Mac OS Catalina
- **NDK version(e.g., 15c)**:  r15c
- **GCC version : 4.2.1 
- **MACE version : v0.12.0-0-ga610d506
- **Python version :  2.7
- **Bazel version : 0.13.1

### Model deploy file (*.yml)
```yaml
library_name: lstm
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  LSTM:
    platform: tensorflow
    model_file_path: ./convert_tf_to_mace/frozen.pb
    model_sha256_checksum: d89fcfb4b68f029d2c6a3056e0ae81d81268ecf2db9da8b892a893a0cb0ccd17
    subgraphs:
      - input_tensors:
          - inputs
        input_shapes:
          - 1,32,80
        output_tensors:
          - labels_output
        output_shapes:
          - 1,37
    runtime: cpu
    winograd: 0

```

### Describe the problem
I am facing a problem when i run this command "python tools/python/convert.py --config path/to/model.yaml" using my own model. my model is LSTM using tensorflow framework. my friend trained that model and gave that model to me. I've already succeeded run the example project from the tutorial and i think i don't have problem with my  env requirements. Please help me find out this problem.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file (my problem occured here)
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Traceback (most recent call last):
  File "tools/converter.py", line 1151, in <module>
    flags.func(flags)
  File "tools/converter.py", line 816, in convert_func
    convert.convert(configs, MODEL_CODEGEN_DIR)
  File "tools/python/convert.py", line 75, in convert
    mace_model = convert_model(model_conf)
  File "tools/python/convert.py", line 168, in convert_model
    option, conf["model_file_path"])
  File "tools/python/transform/tensorflow_converter.py", line 320, in __init__
    self.update_output_shapes(session)
  File "tools/python/transform/tensorflow_converter.py", line 387, in update_output_shapes
    feed_dict=self._placeholders)
  File "/Users/ramaputra/Library/Python/2.7/lib/python/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/Users/ramaputra/Library/Python/2.7/lib/python/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/ramaputra/Library/Python/2.7/lib/python/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/Users/ramaputra/Library/Python/2.7/lib/python/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'bidirectional_2/while_1/Merge' has inputs from different frames. The input 'bidirectional_2/while_1/NextIteration' is in frame ''. The input 'bidirectional_2/while_1/Enter' is in frame 'bidirectional_2/while_1/while_context'.
``
