### ISSUE TITLE
How to compose YAML file if the model has multiply outputs?? 

### ISSUE THREAD

**Issue by bluelml** [XiaoMi/mace#62]
Such as mobilenet-ssd, or mtcnn? How to set the "output_tensors", "output_shapes " in YAML file?
Could you give an example?

**Comment by nolanliou** [comment]
```
     subgraphs:
     - input_tensors:
         - input0
         - input1
       input_shapes:
         - 1,224,224,3
         - 1,224,224,3
        output_tensors:
          - output0
          - output1
        output_shapes:
          - 1,1001
          - 1,1001
```
