### ISSUE TITLE
Model output is different on pocofone/rk3399

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#656]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **NDK version(e.g., 15c)**: 18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: 0.13.0
- **Python version(2.7)**: 3.6
- **Bazel version (e.g., 0.13.0)**: 0.16.0
- **CMake version**: 3.16.0

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: FD
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  RF: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /models/model.prototxt
    weight_file_path: /models/model.caffemodel
    # sha256_checksum of your model's pb file.
    # use this command to get the sha256_checksum --> sha256sum path/to/your/pb/file
    model_sha256_checksum: 98f9b69a085e7d8f40704ac6b2fedae0fda876fff4658509dde3d74d883a9684
    weight_sha256_checksum: a9f5d4dfe944315511c6070e8556790409ae0f0bd9005c5db66b4fdd5c38b716
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,112,112
        input_data_formats:
          - NCHW
        output_tensors:
          - fc1
        output_shapes:
          - 1,1,1,512
    obfuscate: 0
    runtime: gpu
    winograd: 4
```

### Describe the problem
I'm running the same model (same yml configuration) with the same input on two different devices. On one device (pocofone) validation fails, while in the other device (rk3399) validation is successful, that means model output is different on the two devices.

Pocofone:
```
* Validate with caffe
Pull /data/local/tmp/mace_run/model_out_fc1 to build/model/_tmp/spaghnet/99db22d0b7ac3c58eb583284e384f174/POCOF1_sdm845/arm64-v8a
fc1 MACE VS CAFFE similarity: 0.977647651706497 , sqnr: 21.606371365921554 , pixel_accuracy: 1.0
ERROR: [] /mace/validate.py:122: ******************************************
          Similarity Test Failed          
******************************************
```
RK3399:
```
* Validate with caffe
Pull /data/local/tmp/mace_run/model_out_fc1 to build/spaghnet/_tmp/spaghnet/99db22d0b7ac3c58eb583284e384f174/TPS980P_rk3399/arm64-v8a
fc1 MACE VS CAFFE similarity: 0.9997036270419069 , sqnr: 1615.394923043025 , pixel_accuracy: 1.0
******************************************
          Similarity Test Passed          
******************************************

Validation done!
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
2. python tools/converter.py run --validate --layers 0:-1 --disable_tuning --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.

### Additional context
Model to reproduce the issue can be found [here](https://drive.google.com/drive/folders/1toEaoMyZNCJPwg0yH34wNps1lsxjsJDG?usp=sharing)

At the above link it's also possible to find `csv` files related to validation per layer on the two devices (`pocofone.csv` and `rk3399.csv`). @lu229
