### ISSUE TITLE
GPU slow because of Transpose and BufferTransform (not present in cpu mode)

### ISSUE THREAD

**Issue by davidenitti** [XiaoMi/mace#675]
GPU inference is slow because of Transpose and BufferTransform (which are not present in cpu mode).
This is probably because the model is from pytorch and thus NCHW.
How can I avoid this?

### System information
- **OS Platform and Distribution: 19.10
- **NDK version: r15c
- **GCC version : gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
- **MACE version: v0.13.0-0-g9a06864a
- **Python version: 3.7.5
- **Bazel version: 0.13.1

### Model deploy file (*.yml)
```
library_name: model
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  resnet_model:
    platform: onnx
    model_file_path: mod.onnx
    model_sha256_checksum: ded5730f296a60259204f545cbb7ec723fdc8696807e712d477df0684c1f585f
    subgraphs:
      - input_tensors:
          - input
          - input2
        input_shapes:
          - "1,20,240,426"
          - 1,3,760,1352
        output_tensors:
          - output
        output_shapes:
          - 1,3,760,1352
        input_data_formats:
          - NCHW
          - NCHW
        backend: pytorch
    runtime: gpu
    winograd: 0
......
```

### Describe the problem
GPU inference is slow because of Transpose and BufferTransform (which are not present in cpu mode).
This is probably because the model is from pytorch and thus NCHW.
How can I avoid this?

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py run --config=small.yml --debug_mode
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
```bash
I mace/utils/statistics.cc:344]
I mace/utils/statistics.cc:344] --------------------------------------------------------------------------------------------------
I mace/utils/statistics.cc:344]                                          Stat by Op Type
I mace/utils/statistics.cc:344] --------------------------------------------------------------------------------------------------
I mace/utils/statistics.cc:344] |         Op Type | Count | Avg(ms) |      % |    cdf% |           MACs |  GMACPS | Called times |
I mace/utils/statistics.cc:344] --------------------------------------------------------------------------------------------------
I mace/utils/statistics.cc:344] |       Transpose |     4 | 770.851 | 67.392 |  67.392 |              0 |   0.000 |            4 |
I mace/utils/statistics.cc:344] | BufferTransform |     7 | 194.410 | 16.996 |  84.388 |              0 |   0.000 |            7 |
I mace/utils/statistics.cc:344] |          Conv2D |     5 | 102.679 |  8.977 |  93.365 | 11,896,317,504 | 115.859 |            5 |
I mace/utils/statistics.cc:344] |          Concat |     1 |  39.423 |  3.447 |  96.811 |              0 |   0.000 |            1 |
I mace/utils/statistics.cc:344] |         Eltwise |     6 |  26.328 |  2.302 |  99.113 |              0 |   0.000 |            6 |
I mace/utils/statistics.cc:344] |  ResizeBilinear |     1 |   5.365 |  0.469 |  99.582 |    222,139,008 |  41.405 |            1 |
I mace/utils/statistics.cc:344] |      Activation |     1 |   4.779 |  0.418 | 100.000 |              0 |   0.000 |            1 |
I mace/utils/statistics.cc:344] --------------------------------------------------------------------------------------------------
I mace/utils/statistics.cc:344]
I mace/utils/statistics.cc:344] ----------------------------------------------------------
I mace/utils/statistics.cc:344]            Stat by MACs(Multiply-Accumulation)
I mace/utils/statistics.cc:344] ----------------------------------------------------------
I mace/utils/statistics.cc:344] |          total | round | first(G/s) | avg(G/s) |   std |
I mace/utils/statistics.cc:344] ----------------------------------------------------------
I mace/utils/statistics.cc:344] | 12,118,456,512 |     1 |     10.595 |   10.595 | 0.000 |
I mace/utils/statistics.cc:344] ----------------------------------------------------------
I mace/utils/statistics.cc:344] -------------------------------------------------------------------------
I mace/utils/statistics.cc:344]                           Summary of Ops' Stat
I mace/utils/statistics.cc:344] -------------------------------------------------------------------------
I mace/utils/statistics.cc:344] | round | first(ms) | curr(ms) |  min(ms) |  max(ms) |  avg(ms) |   std |
I mace/utils/statistics.cc:344] -------------------------------------------------------------------------
I mace/utils/statistics.cc:344] |     1 |  1143.835 | 1143.835 | 1143.835 | 1143.835 | 1143.835 | 0.000 |
I mace/utils/statistics.cc:344] -------------------------------------------------------------------------
I mace/utils/statistics.cc:344]
I mace/utils/statistics.cc:344] 25 ops total.
I mace/libmace/mace.cc:682] Destroying MaceEngine

```
