### ISSUE TITLE
Android NDK: Undefined reference to MaceEngineConfig destructor

### ISSUE THREAD

**Issue by serviceberry3** [XiaoMi/mace#697]
### System information
- **OS Platform and Distribution**: Ubuntu 20.04
- **NDK version**: 15c
- **MACE version**: v1.0.0-0-g0945e498
- **Python version**:  3.8.5
- **Bazel version**: 0.13.0

### Model deploy file (*.yml)
```yaml

library_name: videopose3d_model
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  videopose3d_model: 
    platform: onnx
    model_file_path: /home/nodog/VENV/opt/model.onnx
    model_sha256_checksum: 478f8988270bf921ce4c3ac4a2c7851e975ac70d7e2baeaad53f8d62434753cc
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 2,272,17,2
        output_tensors:
          - output
        output_shapes:
          - 2,30,17,3
        input_data_formats:
          - NONE
        backend: pytorch
    runtime: cpu+gpu
    winograd: 1
```

### Describe the problem
I converted an ONNX model to mace successfully and added the .data and .pb files to my assets folder in my Android project. I'm trying to run the following native code in my app, in a file called mace_engine.cpp (focus on the loadModel() function):
```cpp
#include <jni.h>
#include <string>
#include <mace/public/mace.h>
#include <fstream>

using namespace mace;
using namespace std;

#define USE_GPU 1

#include <chrono>
#include <android/bitmap.h>

string string_from_jni(JNIEnv *env, jstring& s)
{
    jboolean isCopy;
    const char *convertedValue = (env)->GetStringUTFChars(s, &isCopy);
    std::string r = std::string(convertedValue);
    env->ReleaseStringUTFChars(s, convertedValue);
    return r;
}

class ModelData
{
    public:
        std::shared_ptr<mace::MaceEngine> engine;
};


//mace::MaceEngineConfig::~MaceEngineConfig() = default;



extern "C" {
    JNIEXPORT jstring JNICALL Java_com_example_jni_NdkHelper_stringFromJNI(JNIEnv* env, jobject /* this */) {
        std::string hello = "Hello from C++";
        return env->NewStringUTF(hello.c_str());
    }


    JNIEXPORT jlong JNICALL Java_com_example_jni_NdkHelper_loadModel(JNIEnv *env,
            jobject thiz, jstring cache_dir, jstring model_data, jstring model_pb) {

        string files_dir_ = string_from_jni(env, cache_dir);
        string yoga_classifier_data_ = string_from_jni(env, model_data);
        string yoga_classifier_pb_ = string_from_jni(env, model_pb);

        const std::string storage_path = files_dir_;

        #if USE_GPU
            DeviceType device_type = DeviceType::GPU;

            MaceStatus status;
            MaceEngineConfig config(device_type);
            std::shared_ptr <GPUContext> gpu_context;


            gpu_context = GPUContextBuilder()
                    .SetStoragePath("/home/nodog/docs/asp/VideoPose3D/app/src/main/assets") //where to save OpenCL binaries generated for GPU
                    .Finalize();
            config.SetGPUContext(gpu_context);

            //specify priority of the task
            config.SetGPUHints(
                    static_cast<GPUPerfHint>(GPUPerfHint::PERF_NORMAL),
                    static_cast<GPUPriorityHint>(GPUPriorityHint::PRIORITY_LOW));
        #else
            DeviceType device_type = DeviceType::CPU;
            MaceStatus status;
            MaceEngineConfig config(device_type);
        #endif


        std::ifstream yoga_classifier_data_in(yoga_classifier_data_, std::ios::binary);


        std::vector<unsigned char> yoga_classifier_data_buffer(
                (std::istreambuf_iterator<char>(yoga_classifier_data_in)),
                (std::istreambuf_iterator<char>()));
        std::ifstream yoga_classifier_pb_in(yoga_classifier_pb_, std::ios::binary);
        std::vector<unsigned char> yoga_classifier_pb_buffer(
                (std::istreambuf_iterator<char>(yoga_classifier_pb_in)),
                (std::istreambuf_iterator<char>()));

        size_t data_size = yoga_classifier_data_buffer.size();
        size_t pb_size = yoga_classifier_pb_buffer.size();
        std::shared_ptr <mace::MaceEngine> engine;

        std::vector <std::string> input_names = {"input"};
        std::vector <std::string> output_names = {"output"};

        MaceStatus create_engine_status = CreateMaceEngineFromProto(&yoga_classifier_pb_buffer[0],
                                          pb_size,
                                          &yoga_classifier_data_buffer[0],
                                          data_size,
                                          input_names,
                                          output_names,
                                          config,
                                          &engine);



        if (create_engine_status != MaceStatus::MACE_SUCCESS) {
            return 0;
        }

        ModelData *result = new ModelData();
        result->engine = engine;
        return long(result);

    }

}

```

### To Reproduce
Steps to reproduce the problem:
```
include the mace includes in my CMakeLists.txt with include_directories()
Run a build in Android Studio.
```

### Error information / logs
Please include the **full** log and/or traceback here.
```
../../../../src/main/cpp/mace_engine.cpp:111: error: undefined reference to 'mace::MaceEngineConfig::~MaceEngineConfig()'
```

### Additional context
(111 is where the loadModel() function ends.) It seems to find an issue destructing the instance of MaceEngineConfig that I create. I noticed that this destructor was set to default in libmace/mace.cc. Any ideas?

Thanks a lot.
