### ISSUE TITLE
Crash when trying to run model benchmark

### ISSUE THREAD

**Issue by muendelezaji** [XiaoMi/mace#712]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **NDK version(e.g., 15c)**: 18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 7.5.0 (OS default)
- **MACE version (Use the command: git describe --long --tags)**: v1.0.2-0-gd5ae855a
- **Python version(2.7)**: 3.6.9
- **Bazel version (e.g., 0.13.0)**: N/A

### Model deploy file (*.yml)
`/mace-models/mobilenet-v1/mobilenet-v1.yml`
```yaml
library_name: mobilenet-v1
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

### Describe the problem
Attempting to benchmark the Mobilenet v1 model after building for GPU runtime on arm64-v8 platform. The `run_model.py` script crashes and exits around 50%

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. RUNTIME=GPU QUANTIZE=OFF bash tools/cmake/cmake-build-arm64-v8a.sh
3. python tools/python/run_model.py --benchmark --config=/root/workspace/mace-models/mobilenet-v1/mobilenet-v1.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
CMD> bazel build //mace/proto:mace_py
/bin/sh: 1: bazel: not found
/bin/sh: 1: bazel: not found
WARNING: /root/workspace/MACE/tools/python/py_proto/__init__.py:37: No bazel, use cmake.
CMD> bash tools/cmake/cmake-generate-proto-py-host.sh
CMAKE_VERSION: 3.10.2
CMAKE_INSTALL_PREFIX: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /root/workspace/MACE/build/cmake-build/host
[  0%] Performing build step for 'protoc_bin'
[  1%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/arena.cc.o
[  2%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/extension_set.cc.o
[  2%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/arenastring.cc.o
[  2%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/generated_message_table_dr
iven_lite.cc.o
[  3%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/message_lite.cc.o
[  4%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/generated_message_util.cc.
o
[  4%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/implicit_weak_message.cc.o
[  5%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/int128.cc.o
[  5%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/strutil.cc.o
[  6%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/io/zero_copy_stream.cc.o
[  7%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/io/coded_stream.cc.o
[  8%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/bytestream.cc.o
[  9%] Building CXX object CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/structurally_valid.c
c.o
...
...
...
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/libprotobuf-lite.dir/build.make:302: recipe for target 'CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/repeated_field.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/repeated_field.cc.o] Error 4
CMakeFiles/libprotobuf-lite.dir/build.make:278: recipe for target 'CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/message_lite.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/message_lite.cc.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
c++: internal compiler error: Killed (program cc1plus)
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/libprotobuf-lite.dir/build.make:350: recipe for target 'CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/common.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/common.cc.o] Error 4
CMakeFiles/libprotobuf-lite.dir/build.make:566: recipe for target 'CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/time.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/time.cc.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
CMakeFiles/libprotobuf-lite.dir/build.make:422: recipe for target 'CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/status.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/stubs/status.cc.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.

CMakeFiles/libprotobuf-lite.dir/build.make:590: recipe for target 'CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/wire_format_lite.cc.o' failed
make[6]: *** [CMakeFiles/libprotobuf-lite.dir/root/workspace/MACE/build/cmake-build/host/third_party/protoc/src/protoc/src/google/protobuf/wire_format_lite.cc.o] Error 4
Please submit a full bug report,
```

### Additional context
N/A
